### ISSUE TITLE
GUI for CCDD in JS

### ISSUE THREAD

**Issue by lopezdp** [nasa/CCDD#1]
I will be working as an intern at JSC this summer and the instructions I was sent regarding my assignment is to develop a GUI in JavaScript for a Command & Data Dictionary. I am interested in learning as much as possible about this project and would like to get involved sooner than later. Is this the same CCDD referred to in my assignment? What would be a good way to get started? What tasks or issues can I help you work on now? Thanks and I look forward to working with you.

**Comment by KevinMcCluney** [comment]
Not a program issue
