### ISSUE TITLE
Enhancement: Keyboard shortcuts to move between cells in table editing view

### ISSUE THREAD

**Issue by 9a3eedi** [nasa/CCDD#107]
This is more of a feature request:

While filling in the cells for a command as instructed in the tutorial (Section 3.14) I noticed myself instinctively pressing the tab button to move to the next cell. However, this does not work, and instead adds a tab character to the text inside the cell, which is not what most people would want to do in 99% of cases, in my opinion. I then noticed that there is no way to navigate between cells using tab or arrow keys, and I find myself constantly having to reach for the mouse to move to the next cell. 

The enter button does work, and that takes you to the next cell after inputting, but I noticed it not working for combo box cells.  This is the only shortcut available from what I can tell and it would be good to have additional shortcuts to move around the grid, which will really ease bulk data entry.

**Comment by KevinMcCluney** [comment]
The following will be included in the next version:

- If the Tab key is pressed while editing a cell then the behavior is identical to the Enter key - editing stops in the current cell and begins in the next cell
- If the Tab key is pressed while a cell has focus, but is not in edit mode, then the next cell is selected and editing begins in that cell
- Pressing the Escape key stops editing in the current cell and the cell retains focus (currently it behaves this way if no change has been made to the cell; however, if a change has been made then editing stops but focus is lost)
- Structure tables with a value in the enumeration column restrict the data types available in the data type cell combo box. The default cell editor was incorrectly specified; this has been changed to the ComboBoxCellEditor which allows for keyboard selection of the data type  

If a table cell is in edit mode then the arrow keys navigate within the cell.  If no cell is being edited then the arrow keys navigate between cells.
