### ISSUE TITLE
Store telemetry scheduler information

### ISSUE THREAD

**Issue by mVanSteen** [nasa/CCDD#109]
While trying to understand the working of the scheduler, I tried to store the information and I get a systematic error.
The error appears directly on the main window of CCDD (the log with the database) : 

Failed to store internal table '__tlm_scheduler'; cause 'Invalid SQL command; ERROR: INSERT has more expressions than target columns  Position: 104'

It is followed by a message saying : '__tlm_scheduler stored'

During this operation nothing is stored and closing the telemetry scheduler window loses all progress.

While experimenting, I added an additional column to the previously mentioned table and tried to save it again. The store command resulted no more error but when looking at the table the information that I supposed where supposed to be stored in the row_num column are stored in the newly created column.

Thank you for the help

**Comment by KevinMcCluney** [comment]
There's a bug in the telemetry scheduler output code.  the permanent fix will be in the next release.  I'm working on uploading a corrected .jar file.

**Comment by KevinMcCluney** [comment]
An updated jar file has been uploaded.  It should show as version 2.1.4c.
