### ISSUE TITLE
Variable not registering in the Telemetry Scheduler

### ISSUE THREAD

**Issue by mVanSteen** [nasa/CCDD#110]
Variables created in structure table with a specified rate will most often not appear in the Telemetry Scheduler. Current work around is to toggle the require check box (flicking it on or off works) for the rate parameter in the Table Type Editor in the structure tab.

Reproduction of the problem
1) I created a test structure and some variables and stored them as shown below : 
![image](https://github.com/nasa/CCDD/assets/149176027/d7ca692b-76c6-4218-bbdc-480f3f0aecf1)

2) Looking to the telemetry scheduler, both linked and unlinked variables are greyed out and there is no sign of the newly created variables 
![image](https://github.com/nasa/CCDD/assets/149176027/36a091bc-e1c8-4593-bb0a-b58de637f137)

Current work around:
1)  Open the Table Type Editor in the structure tab 
![image](https://github.com/nasa/CCDD/assets/149176027/7c70ad7e-c5f6-4c66-b436-de632ec74804)

2) Toggle the required check box (on or off) for the rate parameter and Store the information 
![image](https://github.com/nasa/CCDD/assets/149176027/b0497b9b-7b43-4782-9de2-41bda34b48aa)

3) The variables now appear as they should in the Telemetry Scheduler
![image](https://github.com/nasa/CCDD/assets/149176027/1320d8ad-3889-4691-a0b0-9908b4dbce93)

I might do something wrong or forgetting something but I could not figure it out with the Documentation.
Thank you for the help :)

**Comment by KevinMcCluney** [comment]
A correction has been pushed to GitHub; the new version is 2.1.4e.

Details: The SQL functions get_def_columns_by_name() and get_def_columns_by_index() include retrieval of rate column information if a rate column exists.  At the point where these functions are initially built the rate parameters have not been determined.  This resulted in the rate column retrieval being omitted from the functions.  The correction is to read the rate parameter prior to building the functions.

Altering the rate column in the table type editor causes the functions to be rebuilt.  At that point the rate parameters have been read, so the functions were altered to include the rate column retrieval.
