### ISSUE TITLE
Problems with the copyTable.js script 

### ISSUE THREAD

**Issue by mVanSteen** [nasa/CCDD#111]
I think there are some errors/typos in the copyTable.js script  (and the ones in other languages). Correcting the following lines in the file seems to fix the problem for me.

change line 111:
_if (tlmMsgIDs[index][0] == usedHKNames[index])_
to :
_if (tlmMsgIDs[msgIndex][0] == usedHKNames[index])_

change line 130:
_var copyTableEntries = ccdd.getCopyTableEntries(copyTables[copyTable], CCSDS_HEADER_LENGTH, "Message ID Name", true);_
to:
_var copyTableEntries = ccdd.getCopyTableEntries(copyTables[copyTable], CCSDS_HEADER_LENGTH, "Telemetry message name & ID", true);_

I could just have forgotten something but those lines seem strange to me and produced the expected output after some testing.
Thank you for the help

**Comment by KevinMcCluney** [comment]
Thanks for information! The scripts have been altered and uploaded. Since the message ID name is user-defined, the script would need to be updated to match the project.  As the default it makes sense to use the message ID name in the tutorial.
