### ISSUE TITLE
execute interprets absolute path as association name

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#13]
For robustness against where the user runs and/or places CCDD on their machine, I'd like to use absolute paths. When attempting to specify an absolute path to the script file, as shown in the command below:

```java -cp C:\My\Absolute\CCDD\Path\CCDD.jar CCDD.CcddMain -logPath C:\My\Absolute\Log\Path -project myProject -user myUser -password #### -execute 'C:\My\Absolute\Script\Path\myScript.js:Group:myGroup' -scriptOutPath C:\My\Absolute\Out\Path```

I get the error:
`CCDD : Database Error : Unrecognized association name 'C'`

at the command line. It appears that it may be parsing the colon in the path as the separator in the script definition. Using a relative path to the script (which doesn't include a colon) works as intended.

**Comment by KevinMcCluney** [comment]
The colon following the drive letter caused a parsing issue.  This is corrected in the latest version (1.2.39) uploaded today (6/11/2018).
