### ISSUE TITLE
Longer stack trace for errors in scripts

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#14]
The error handling for the scripting interface only logs the top of the stack trace, which complicates script debugging.

The following are an examples of error messages printed to the log upon encountering an error in a script:

```
localhost:5432|myProject|myUser|06/18/2018 12:18:58.002|Fail|Cannot execute script 'C:\my\path\to\script\myScript.py' using table(s) 'Group:myGroup'; cause 'script file 'C:\my\path\to\script\myScript.py' error 'TypeError: 'str' object is not callable in <script> at line number 432''
```
```
localhost:5432|myProject|myUser|06/18/2018 12:22:08.366|Fail|Cannot execute script 'C:\my\path\to\script\myScript.py' using table(s) 'Group:myGroup'; cause 'script file 'C:\my\path\to\script\myScript.py' error 'AttributeError: 'array.array' object has no attribute 'length' in <script> at line number 432''
```

In both cases the error is reported as having occurred on line 432, which (for this script) is the top-level parent function in the call stack in which the error occurred. In my case, this is a large helper function which implements the entire algorithm and these errors occurred in two different child functions, which can be complicated to track down. It would be very helpful to log longer/deeper stack traces. 

Thanks

**Comment by KevinMcCluney** [comment]
The script languages generally provide little exception information to the Java script engine (how much information is script language dependent).  However, you can get more information by amending the scripts with exception catching.
For example, in a Python script a try-except clause can be added.  The clause can encompass the main script steps (versus individual functions):

import traceback
try:
    # Main python steps that call other functions, etc.
    .
    .
    .
except:
   raise Exception(traceback.format_exc())

If an error occurs in the script then the except: clause passes more information back to CCDD that then appear in the event log.  Note that you can append other information to the Exception string to passed back to CCDD, or perform formatting on the trace to make it more readable.

**Comment by ascended121** [comment]
Thanks! That workaround is good enough for me!
