### ISSUE TITLE
Methods of inspecting script values at runtime

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#15]
It would be very useful to be able to inspect values within CCDD scripts at runtime, which I don't believe is currently possible. This capability could be utilized for script development/debugging and could also be used for archiving the status/state/results of scripts beyond the success/fail that is currently logged.

Exposing a method in the scripting API to allow writing a message to the CCDD log file may be one way to provide this capability. Its currently possible to write short strings to the showErrorDialog/showWarningDialog methods, but dismissing those dialogs requires user interaction and does not appear to result in a log entry.

Thanks

**Comment by KevinMcCluney** [comment]
The only way I know to monitor script values during runtime is to embed print statements.  

I'm adding three script data access methods, which will be available beginning with CCDD version 1.2.46: **writeSuccessLogEntry(String logMessage)**, **writeFailLogEntry(String logMessage)**, and **writeStatusLogEntry(String logMessage)**.  These output a success, fail, and status log event respectively in the form: "[script: _scriptFileName_] _logMessage_".

**Comment by ascended121** [comment]
I've had a bit of time to play with these and have noticed that they don't appear to emit a log entry if passed an empty string, which was a bit unexpected (I'd expect to see an empty log entry), but not necessarily a problem. Very helpful for keep track of what scripts are doing! Thanks!

**Comment by KevinMcCluney** [comment]
I had it reject null or empty log entries, but maybe there's a need for those.  I changed the event message script access methods so that an empty string is allowed (nulls are converted to an empty string).
