### ISSUE TITLE
Export does not export macro definitions 

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#16]
The current export format (at least for CSV and JSON) does not contain a definition of the project macros. The dialog contains an option to substitute macro values for macro names, however this doesn't preserve the definition of the macro.

I'm using macros to define and ensure that enumeration values stay in sync. For example, if two packets telemeter the same type of enumeration, its desirable to have a single definition for that enumeration to eliminate the possibility of them accidentally being defined differently. This is achievable via macros (ie, define a macro containing the definition of the enumeration and then use the macro in the enumeration field of both table rows), however the value of the enumeration is not exported unless the substitute option has been checked, in which case the single definition of both enumerations is lost when imported.

I think it would be useful to export the definition of the macro if the substitute option is not selected (so that the user has access to the macro values) and to import macro definitions if found in the file being imported.

**Comment by KevinMcCluney** [comment]
The behavior you describe is the way the program is supposed to be operating.  However, the JSON export has a bug in that it inverts the check box selection for substituting macros (i.e., if "Replace macros" is checked it retains them instead) - this will be corrected in the next release.  The macro definitions appear under "Macro Definition" in the output.  The CSV export is working as expected (it correctly retains macros with the check box unchecked), and it includes the macro definitions under the tag '_macros_'.  The macro definitions are imported if found in the import file.

**Comment by ascended121** [comment]
Can confirm that the json macro replacement checkbox is inverted, and when macros are not replaced in the output there is a definition of the macro under a "Macro Definition" element.

I just tried it again and do not see a `macros` tag in the csv output. The replacement checkbox seems to be working as intended for CSV... when the setting is checked I see the value of the macros in the output and when not checked I see the macro name, but I don't see the definition of the macro with either setting.

**Comment by KevinMcCluney** [comment]
Can you attach a copy of the CSV file that has a macro in a table value but no macro definitions?  This would be helpful in locating the cause of the problem.

**Comment by ascended121** [comment]
Experimenting a bit more, I noticed that whether or not I get macro definitions depends on where the macro is used... I do get macro definitions if I use the macro in the description field of a row but I do not get macro definitions if the macros are ONLY used in the enumeration field of a row. Currently the only place I'm using macros is to define enumerations (to ensure that they're consistently defined for multiple rows), which is why I wasn't seeing any macro definitions.

It appears that there might be some logic to only export macros which are actually used in the tables and that logic is not looking at the enumeration field?

**Comment by KevinMcCluney** [comment]
That information was very helpful!  I located the issue and corrected it.  The update is in the current release.
