### ISSUE TITLE
Execute command output path subcommand

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#17]
The scriptOutPath command is provided to control the placement of files created by scripts via the command line interface (CLI), which works as intended, however that command also changes the output path for users interacting with CCDD via the GUI (which may not be desirable).

To support workflows in which CCDD is used both as an editing/development interface (via the GUI) and as a data producer (via the CLI), it would be desirable to be able to set the output of scripts for a particular session, which wouldn't affect later GUI users. Currently, if scripts are called in between GUI sessions the output path may have unexpectedly (to the GUI user) changed.

Additionally, the CLI supports multiple execute commands, which effectively means that all outputs from a given session must be placed in a single output directory. This may be undesirable if several scripts producing different output are called during a single CCDD command. 

It would be useful if the execute command took (an optional) subcommand allowing the specification of a path which overrides the CCDD global script output path set by setOutPath for a particular execute command. This allows organization of the outputs of multiple script calls and allows CLI users to execute CCDD scripts without modifying the state of CCDD, which may be confusing for GUI users. This would maintain the current functionality of scriptOutPath command but also support the points above. This also mirrors the functionality of the filePath subcommand of the export command.

Thanks

**Comment by KevinMcCluney** [comment]
The following changes are in the next release:
1) The scriptOutPath, logPath, and filePath command line commands only change these paths for the current session.  When the session closes, the paths revert to their original values.  This is true if the GUI is displayed or not.
2) The scriptOutPath can be used more than one.  The order of the scriptOutPath and execute commands determines how the path is applied - an execute command uses the previous scriptOutPath command value.  If no value is set then the one stored in the program preferences is used.

**Comment by ascended121** [comment]
Thanks, just tested and can confirm that scriptOutPath changes are no longer persistent and that it properly sets the output path when run before the execute command.
