### ISSUE TITLE
Fields with boolean type not displayed as check box

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#18]
When adding custom columns to the default structure table, the user's guide indicates that a check box will be used to represent boolean fields when editing tables. In practice a text field is present to the user which only accepts `true` or `false`. This works, but doesn't appear to be consistent with the user guide and results in having to handle an additional option (true, false, or empty) in script logic.

In built-in tables such as the Table Type Editor, the Unique and Required fields do correctly display as check boxes, so perhaps just user-defined fields are not being formatted?

**Comment by ascended121** [comment]
Understood, I would rate this as a low priority request since the current method works and doesn't significantly complicated script logic. Thanks

**Comment by KevinMcCluney** [comment]
I made changes so that boolean columns appear as check boxes.  As expected the changes span a large number of classes and methods.  I don't plan on releasing this until I can do sufficient testing.
