### ISSUE TITLE
MsgIDs applied to non-root tables

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#19]
When using the Message IDs > Assign IDs menu to apply message IDs to structure tables, Message IDs are applied to all structure tables, not just root tables. This results in child tables being assigned Message IDs.

Structure tables (by default) have two fields, `Telemetry Message ID` and `Telemetry Message ID Name`. These fields have applicability set to `Root Only`. This setting seems to control whether the Data > Edit Tables editor displays the Message ID field for editing. It seems like the Assign IDs menu should respect the Root Only setting of that field.

**Comment by KevinMcCluney** [comment]
Concur with your assessment.  The next release will have the change incorporated.
