### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by jasonduley** [nasa/CCDD#2]
can you please add a License file to the root of the repo when you get a chance? Thanks.

**Comment by KevinMcCluney** [comment]
I’m unsure what to put in the file, other than the copyright notice.  If you have any direction please let me know.

**Comment by jasonduley** [comment]
Kevin, contact your center SRA for details and also look at other NASA projects on GitHub for examples.  Thanks.

**Comment by lopezdp** [comment]
@KevinMcCluney I was looking at this resource recently as I had a similar question regarding Licenses and this might help you decide what to use based on NASA guidelines and requirements, etc.

https://choosealicense.com/

**Comment by KevinMcCluney** [comment]
Status: The JSC legal office is looking into the proper license format.

**Comment by KevinMcCluney** [comment]
Per JSC Legal the appropriate license is the NASA Open Source Agreement (NOSA).  This has been added to the license file.
