### ISSUE TITLE
Feature Request: Enumerated Value input type

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#20]
It would be useful to have an enumerated input type to constrain user inputs to one of a set of predefined values, preferably via a drop-down menu of options. This would be distinct from the current `Enumerated` input type, which is simply validated as an alphanumeric field.

I'm looking at tracking CFS event messages via a custom table type and need to track the event type (which is either 'Debug', 'Info', 'Error', or 'Critical'). It would be useful to have an input type which could validate the input is one of the items in a list of acceptable values. Otherwise, an unacceptable input cannot be caught until a script which depends on that value runs and throw an error.

Another potential use case may be in defining CFS limit tracker watchpoints where the user must select one of a pre-defined list of operations to be performed (LessThan, EqualTo, GreaterThan, etc) by the watchpoint.

**Comment by KevinMcCluney** [comment]
Great suggestion!  I've contemplated adding an editor for entering custom input data types and this is an example of how that feature could be used.  I'll need to think about how this could be implemented.

**Comment by ascended121** [comment]
A custom input data type would be useful.

Assuming a custom input data type is not available though, one method of implementing this may be to treat enumerations as a first class datatype within CCDD, in the same way that macros and data types are treated (ie, with their own editor window and separate management). A definition of an enumeration would assign a specific set of enumeration mappings a name which could be used in other parts of CCDD (similar to how datatypes currently work).

I envision two types of input data types relating to enumerations... 

1. one which enforces that a user inputs one of a list of enumerated values to the CCDD editor
2. and one which only accepts the name of an enumeration in the CCDD editor

Use cases for these two types on input fields would be:

1. Constraining the user entering data to one of the enumeration values (ie, constraining the user specifying the type of a CFS event to Debug, Info, Error, Critical)
2. Constraining the user entering enumeration for structure table rows to one of the enumeration names defined (ie, to describe the possible values of a flag in a telemetry packet)

Some examples of built-in enumerations provided by CCDD might be an Toggle (ie Enable/Disable), Validity (ie Valid/Invalid), a Boolean (True/False) enumeration, and CCDD would allow the user to add their own definitions (such as CFS Events types, etc).

**Comment by ascended121** [comment]
Just tested with 1.3.1 and works great.
