### ISSUE TITLE
Method to terminate script execution

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#25]
Most of the built-in scripts provide some form of error checking in the main program (ex: checking structure rows exist) and use the showErrorDialog() method to present the error to the user. The flow control in those scripts appear to have been engineered such that showErrorDialog is called just before the script exits, however, for complicated scripts there can be error checking which is not easy to structure in this manner (ex: error checking values of structure columns which are not accessible until much later in the program). 

It would be useful to have a way to cancel/terminate execution of the current script via the API. At least in jython, I've tried using a return statement and sys.exit to terminate the script with no luck.

This give script-writers the ability to decide if an error is recoverable and if not just inform the user and terminate the script, rather than having the user sit through and acknowledge any additional errors during the remaining execution.

**Comment by KevinMcCluney** [comment]
The script can be terminated by inserting a call to throw an exception.  For example, in JavaScript use 'throw new Error("insert error message here");', and in Python use 'raise BaseException("insert error message here")'.
