### ISSUE TITLE
Changes to input type definitions don't take effect until reapplied

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#26]
When designing my own input type field for a column with an enumerated value (ie a set of 'Valid Selections), I noticed that changing the definition of an input field doesn't seem to take effect until that custom input type is reapplied to the column.

Steps to reproduce:

1. Define a custom input datatype with values in the Valid Selections column via the input types editor, store changes
2. Apply that custom input type to a column via the table type editor, store changes
3. Open a table which uses that column, and confirm that the 'Valid Selections' are listed in a dropdown menu and are selectable
4. Back in the input types editor, add additional Valid Selections, store the changes
5. Open same table again, dropdown with Valid Selections doesn't appear, input field appears to just be a standard text input which will accept any value
6. In table type editor, assign that column to any built-in input type, store changes
7. Then, assign column back to custom input type, store changes
8. While editing table, once again able to again see and select from the Valid Selections dropdown

**Comment by KevinMcCluney** [comment]
The custom input type feature is somewhat bug-ridden and incomplete at this time.  Changes are in work.

**Comment by KevinMcCluney** [comment]
The issue described has been addressed.  The implementation of the custom input types is complete.
