### ISSUE TITLE
Feature Request: Numeric input type

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#29]
In would be useful to have an input type which only accepts numeric characters and a single optional period. This is similar to the current Floating Point input, however the floating point input will add a trailing decimal even if the user does not enter one. This numeric input type should preserve the user's input with respect if the decimal exists or not. 

The following regex describes the requested validation:
```
\d*\.?\d*
```

While this can be achieved via the input type editor, this seems like a generic-enough type that it may be worth including by default. I'm looking to use this input type to store literal values of command arguments and variable field, for use in scripts. While it would be ideal to check the value the user entered is consistent with the specified command argument/variable type, I think that ensuring the user enters a numeric value (and preserving what they entered) is sufficient for now.

**Comment by KevinMcCluney** [comment]
Starting with version 1.3.12. a new input type, 'Number', will be supported.  It acts like the Float input type, but removes the trailing '.0' if the value is an integer.  In addition, a new input format type, also called 'Number', is available in the input type editor's 'Value Format' column drop down menu.  This allows applying the same formatting to user-defined input types.
