### ISSUE TITLE
Database Name

### ISSUE THREAD

**Issue by lopezdp** [nasa/CCDD#3]
I am trying to implement a feature on the CCDD_Viewer GUI that displays what database each user is logged into alongside what user name each user is "Signed in As".

I don't see any 'meta' project data that I can pull from the CCDD Tool's web server API. Would it be possible to add an API call that will allow me to pull the project details such as "AA2" so that I can display it on the Viewer's GUI?

Thanks!

**Comment by KevinMcCluney** [comment]
A new web access command, project_info, has been added (see Table 6 in the user's guide for details).  Also, the capability to have projects with capitalization in the name preserved was added.
