### ISSUE TITLE
Feature Request: Variable Reference validation

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#30]
As described in the issue describing its implementation, the variable reference field turns yellow if the reference is not valid (ie, if the referenced variable has changed since the field was selected), which is useful for identifying invalid fields in the table the user is editing. As far as I'm aware, there is currently no way to tell if a change to a structure results in invalid references without opening each table containing a reference and checking for yellow cells.

It would be useful to have a reference validator utility (maybe accessible from the Data menu) which would check all of the variable reference fields in all tables and inform the user if any need to be updated.

**Comment by KevinMcCluney** [comment]
The latest version automatically updates the variable references in the table cells and data fields.  If a variable is renamed then the value in the cells/fields is changed to incorporate the new name.  If the variable is deleted then the cell/field is blanked.
