### ISSUE TITLE
Feature Request: Command Reference/Table Column Reference Input Type

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#31]
Similar to the Variable Reference input type, it would be helpful to have a Command Reference input type for which the valid values are the name of an existing Command Name from a defined Command table. This may be more generally handled by an input type which references a particular column in a particular table type (both defined by the user). It would be helpful if the same autofill that works for the variable reference also worked for this input type to prompt the user with the valid options.

This command reference would be useful for the definition of RTS/ATS tables for which its important that the command the user selects already exists in the database. I don't currently have a specific use case for the general table column reference input type, other than as a more general implementation for the use case of the Command Reference described above.

**Comment by KevinMcCluney** [comment]
The latest version incorporates the two features requested:
(1) A new menu command, 'Show commands', that displays a dialog with project's commands (name, code, table, and argument names), filterable by table.
(2) A new input type, 'Command reference', that provides a drop down menu of all commands (name, code, table, and number of arguments), filterable by entering a match string (wildcards accepted).
