### ISSUE TITLE
Cannot load project

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#32]
With CCDD 1.4.7 I've been unable to load either projects created with older versions of CCDD nor new projects created with this version. When I attempt to load a project I see a long list of queries (~2200 repetitive sets of queries) and after ~10-20sec am presented with:

Cannot obtain command information:
![image](https://user-images.githubusercontent.com/18016749/44607088-371b6580-a7bd-11e8-8826-b94f8b08a652.png)

acknowledging the dialog yields:
![image](https://user-images.githubusercontent.com/18016749/44607077-2a970d00-a7bd-11e8-82ed-bc108797ddee.png)

After these dialogs CCDD displays the project name as if I'm connects but won't allow creation of new tables and attempting to edit existing tables (of which I wouldn't expect there to be any) yields an error due to being unable to load table members.

![image](https://user-images.githubusercontent.com/18016749/44607849-b6aa3400-a7bf-11e8-97e7-96153fecd9e7.png)

and the log viewer displays: 
```
Cannot load table members; cause 'Connection to server lost'
```
After this I'm forced to restart CCDD because all the project options are disabled.

**Comment by ascended121** [comment]
Also noticed that in 1.4.7 I'm not prompted to update projects with user permissions if they don't already have them, as 1.4.5 did. I'm not sure if that's related since I observe the same behavior with 1.4.7 (described above) whether or not the project already has the user permissions implemented.

With 1.4.5 I'm able to load my projects as expected, so I'll stay with that version for now.

**Comment by KevinMcCluney** [comment]
The current version (1.4.14) addresses the issues you encountered.
