### ISSUE TITLE
Export 'All Tables' group from command line

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#33]
I'm attempting to use the command line interface to export all the tables in the database. I've listed the export commands I've attempted below. 

```
-export "-filePath ./ -format json -tablePaths Group:All Tables -singleFile true"
```
Results in:
```
Error: Unrecognized delimiter for command 'Tables'
```

Both
```
-export "-filePath ./ -format json -tablePaths 'Group:All Tables' -singleFile true"
```
and
```
-export "-filePath ./ -format json -tablePaths Group:'All Tables' -singleFile true"
```
result in:
```
CCDD : Database Error : Cannot load table ' '
```

Since `All Tables` has a space in it, I presume I'm supposed to quote the name, but I haven't been able to figure out how to correctly specify the command and am unsure if this is user-error or a bug.

Thanks!

**Comment by KevinMcCluney** [comment]
The pseudo-group is 'All tables' - the 't' in tables is lower case.  The form:
   -tablePaths 'Group:All Tables'
is the correct one.

**Comment by ascended121** [comment]
Ah, user error. 

Also, just tested and can confirm that the child tables are exported correctly in 1.4.27. Thanks!
