### ISSUE TITLE
Exception when attempting to import 

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#34]
I'm seeing the following exception when attempting to import a json file:

![image](https://user-images.githubusercontent.com/18016749/45839821-7026f700-bce3-11e8-9e76-0e8e85a96dd9.png)

I'm observing this on version 1.4.24. The json file was exported by the same version. Happy to provide additional information if needed.

Thanks

Edit: To clarify, this appears to only occur when importing into the same project from which it was exported. It does import correctly into a new project.

**Comment by KevinMcCluney** [comment]
The issue is corrected in version 1.4.27.

**Comment by ascended121** [comment]
Thanks, just tested and can indeed import in 1.4.27.
