### ISSUE TITLE
Feature Request: Create/Delete projects from CLI

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#35]
It would be useful to have the ability to create and delete projects from the command line interface to facilitate using CCDD as a background database. 

I'm attempting to setup CCDD such that when a developer checks out a git branch it loads the correct version of the database into CCDD for them. Currently, if importing tables into an existing project, there's no option which allows for deleting tables not found in the imported file. This means that while tables present in the import can be updated (using 'replaceExisting' option), any tables present in the project (but not in the import) will remain in the project after import.

I believe the easiest solution for this workflow (and in terms of implementation) is to create a new project each time a branch is checked out, which requires the ability to create a project from the CLI and preferably a method of deleting them from the CLI.

**Comment by KevinMcCluney** [comment]
This capability has been added beginning with version 1.4.29.  The commands to create a new project, import tables into the new project, and execute scripts using these tables can be included in the same set of command line arguments.

**Comment by ascended121** [comment]
Thanks, the create/delete commands appear to be working. 

When use the commands in the order `-delete -create -import` I'm getting 
```
CCDD : Database Error : Cannot connect to project 'MY-project'
```
Are those commands intended to be chain-able? That's not necessarily needed, but I'm unsure if it was intended.

Also, I get the following if I attempt to create a project when a project with that name already exists:
```
CCDD : Database Error : Cannot create project 'MY-project'
```
I think it may be helpful to output a more specific message indicating that the project already exists as the current one implies a database issue.

Similarly, when attempting to delete a project which doesn't exist, I get:
```
Error: Delete project 'MY-project' disabled; user lacks administrative access
```
which isn't very intuitive.

**Comment by ascended121** [comment]
It also appears that one cannot delete a project if that project is open in another instance of CCDD (which makes sense). I get the error message:
```
CCDD : Database Error : Cannot delete project 'MY-project'
```
but it may be helpful if could identify the issue a little more specifically.

**Comment by KevinMcCluney** [comment]
The event log message provides the details.  The message sent to the command line is the same one that would be sent to a dialog if the GUI is visible.  The dialog messages are abbreviated by design.

**Comment by ascended121** [comment]
Thanks for referring me to the log. I agree that that does have the required information to diagnose the issue.

For my workflow, I have an external program calling CCDD under the hood so its much preferable for a user to get the specific feedback that they should use a different name than for them to have to go find the CCDD log file and review it for the details of what went wrong and then return to my workflow to try again.  

As an example, I do think that the error string
```
Database Error : database "MY-project" already exists
```
is much more useful to the user in diagnosing the problem, but is not significantly longer than the existing response:
```
Database Error : Cannot create project 'MY-project'
```

I think a similar argument can be made for:
```
Database Error : database "MY-project" is being accessed by other users
```
and the existing message:
```
Database Error : Cannot delete project 'MY-project'
```

**Comment by KevinMcCluney** [comment]
The actual cause that generated the message is provided as part of the exception that's thrown.  For example, the exception that caused the message 'Cannot create project ...' may be because the database already exists, or it may be that the server connection dropped, or it may be a permissions issue, etc.  Since the log is capturing the exception message content the dialogs are kept shorter.  However, I recognize that if running from the command line without the GUI the shorter message is less helpful.  Therefore, I've made the change so that **if the GUI is hidden** then full length message is output to the command line.

**Comment by ascended121** [comment]
Thanks Kevin, appreciate your consideration of these issues.
