### ISSUE TITLE
Feature Request: Export/Import group information

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#36]
It would be useful to have the ability to automatically import/export groups into/out of CCDD.

I'm attempting to setup CCDD such that when a developer checks out a git branch it loads the correct version of the database into CCDD for them. I'm using groups to organize sets of tables by application to make it easy to execute scripts on the set of tables describing that application. Its currently possible to import table types, input types, data types, tables, and macros but not groups, which means grouping information is lost through an export/import cycle.

**Comment by KevinMcCluney** [comment]
Version 1.4.28 supports import and export of group information (including group data fields) in CSV and JSON formats, both from the GUI and the command line.

**Comment by ascended121** [comment]
Thanks! 

I just pulled down 1.4.28 and tried a json export, but I'm having trouble finding the group info in the generated file. In the users guide it looks like there should be an entry in the json called `Group` which contains the grouping info, however searching the file for `Group` in my export yields no results. 

Are there any additional steps that I need to take to get the group export working?

**Comment by KevinMcCluney** [comment]
Did you select the **Include group definitions and data fields** check box in the JSON export dialog (or, if exporting via the command line -export command set the **includeGroups** option to true)?

**Comment by ascended121** [comment]
Ah, thanks, I failed to notice the new checkbox and argument. When selecting the checkbox I do indeed see group information in the output. 

I'm currently getting the following exception when attempting to use the CLI:
```
An unanticipated error occurred; cause 'java.lang.NullPointerException'  Error trace:   CcddJSONHandler: exportToFile() line 1246   CcddFileIOHandler: exportSelectedTables() line 2220   CcddCommandLineHandler: doCommand() line 1099   CcddCommandLineHandlerCommandHandler: handler() line 364   CcddCommandLineHandler: parseCommand() line 1761   CcddCommandLineHandler: parseCommand() line 1627   CcddMain: parseDbSpecificCommandLineCommands() line 847   CcddDbControlHandler: complete() line 2633   CcddBackgroundCommand: done() line 192
```

My export command is `-export "-filePath 'my\output\path.json' -format json -tablePaths 'Group:All tables' -singleFile true -includeGroups true"`

**Comment by KevinMcCluney** [comment]
This is a case of one bug revealing another.  The flags to include groups and to include variable paths were reversed in the command line call to export, so setting includeGroups actually instructed it to include the variable paths.  However, the variable path separators were undefined (null), which is what triggered the exception.  The flags are in the correct order and command line options to set the separators (using default values if not explicitly set) beginning with version 1.4.30.

**Comment by ascended121** [comment]
This appears to be resolved in 1.4.30, I'm able to export via the CLI using the includeGroups flag. Thanks!

**Comment by ascended121** [comment]
I'm attempting to run my scripts on tables imported with grouping information and for the command `-execute my_script.py:Group:MG` I'm seeing the error:
```
Cannot execute script 'my_script.py' using table(s) 'Group:MG'; cause 'Table ' ' (or one of its children) failed to load'
```

A command of the form `-execute my_script.py:Group:Group:MG` is executed successfully. It seems like the import may be prepending `Group:` to each of the imported group names.

Also, looking at the group manager... in my imported project I see the groups listed as `Group:MG` whereas an the project I originally exported from only displays `MG`.

**Comment by KevinMcCluney** [comment]
When CCDD is importing a group the group identifier ("Group:") is erroneously prepended to the group name (this is needed only for a group data field definition).  The database then considers the group's name as "Group:name" instead of just "name", hence having to add an extra "Group:" identifier when referencing it.  The next version released has the correction.
