### ISSUE TITLE
Feature Request: Support for longer project fields

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#39]
Currently it appears that there's a limit of 100 characters on project field widths (though that appears to be a limit on the displayed entry field, rather than a limit on the size of the contents). It would be useful to be able to use longer fields to store project metadata (for example, an overview of the mission and/or subsystem) that doesn't belong in the current CCDD project description field.

The content I'm looking to store is ~7,000 characters long, which would probably be unreasonable for the GUI to support, but something longer than 100 would be useful.

**Comment by KevinMcCluney** [comment]
The data field width has a constraint to prevent trying to display a field wider than the screen.  The default value is 100, but this can be changed under the program preferences 'Size' tab (Maximum data field length).  The maximum allowed is 200 characters.  Note that whatever the length the field can contain any number of characters - the text can scroll as the cursor is moved via the arrow keys.
For a large number of characters (~7000 certainly applies) then set the data field's input type to 'Text (multi-line)'.  The field allows line-feeds (Enter key) and expands in height as more lines are added.  I just noted that the multi-line input types don't pay attention to the maximum width preference value; I need to fix that.

**Comment by ascended121** [comment]
Thanks for the info. I think using the multi-line text input will work with my data (once the maximum width is constrained, as its currently going off my screen). Appreciate the info!

At least to me, the 'Size' label on that column of the field definitions was a bit confusing because I originally assumed that it was referring to the size of the data to be stored (which I imagined might be needed by the database, and corresponded with the Array Size used in other contexts). Through accidentally pasting longer data into the field I discovered that it was in fact a display setting, but changing the label of that column (and maybe the corresponding setting) to 'Display Size' or 'Display Width' may make that more intuitive for some people. I do see that its thoroughly explained in the users guide though.

**Comment by KevinMcCluney** [comment]
The editor column name has been changed to 'Width', and the column header's tool tip text is amended to match.

**Comment by ascended121** [comment]
While the fields now appear to obey the constrains initially, as soon as I move the window or resize the field the vertical scroll bar disappears and the window becomes unusably tall.

**Comment by KevinMcCluney** [comment]
Starting with version 1.4.33 the multi-line data fields have a set number of display rows.  This is user-definable via the preferences dialog: the default number of rows is 3 with a minimum of 1 and a maximum of 25.  Once the number of rows of text exceeds the field's display row size a vertical scroll bar appears alongside the data field (the description field behaves in the same manner).

**Comment by SpaceSteve121** [comment]
Thanks, the windows appear to be better behaved as of 1.4.48 and are no longer becoming unusably tall when moved. Also verified that the number of rows setting is working well. Looks good!
