### ISSUE TITLE
Table creation error

### ISSUE THREAD

**Issue by jongyeob** [nasa/CCDD#4]
Hello,

I installed CCDD on Ubuntu 16.04 64bit, Postgresql 8.4.

When I open my project first, there is an error message.

localhost:5432|-|-|12/28/2017 17:19:07.820|Fail|Cannot load table members; cause 'ERROR: function get_table_members_by_index() does not exist  Hint: No function matches the given name and argument types. You might need to add explicit type casts.  Position: 15'

I attached an error screen.

![2017-12-28 5 51 46](https://user-images.githubusercontent.com/5885949/34405687-faccb9c0-ebf7-11e7-8ce3-e468ed369039.png)

**Comment by KevinMcCluney** [comment]
A correction for this error has been uploaded (on 12/28/2017).

**Comment by lopezdp** [comment]
Kevin gets it done!
