### ISSUE TITLE
All Tables pseudo-group not available when no other groups defined

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#40]
When no groups have been defined by the user, the 'Filter by group' option is grayed out in windows which allow a selection of tables (ie, export menu, scripts menu). This prevents prevents usage of the All tables pseudo-group. It would be handy to be able to use that group regardless of if the user has defined other groups.

**Comment by KevinMcCluney** [comment]
The next version has the group filter check box always enabled
