### ISSUE TITLE
Inconsistent structure table fields

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#44]
My structure table type has a field 'Telemetry message name & ID' with applicability 'Roots Only'. When I edit the prototype of some of my structure tables I'm finding that some of them don't have that field defined. Is this supposed to be possible? My understanding was that all tables of a particular type would have the same columns and fields.

Edit: Observed on 1.4.38

**Comment by KevinMcCluney** [comment]
If the structure table isn't a root table then any field with an applicability of "Roots only" won't be displayed beneath the structure table in the table editor.  This is true for an instance of the table _and for its prototype_.  However, if you open the field editor from the table's prototype (**Field | Manage fields** in the table editor command menu) all of its data fields are displayed in the field editor, even if the field is not currently applicable.

**Comment by ascended121** [comment]
Understood... those tables had no fields defined in the prototype's Manage fields window even though the table type had fields defined. I ended up manually adding those fields to the tables which were missing them (to get my scripts working) but even now I notice that the some of my fields have different Applicability. My fields are defined (in the table type) to have `Roots Only` applicability however some of my table prototypes have those same fields with `All tables` applicability, which I don't believe should be possible. 

Does the import process ensure that all tables of a particular type have the same fields as the table type definition? If not, is that a mechanism through which field definitions might get out of sync?

**Comment by ascended121** [comment]
After going through another import/export cycle, I've now ended up with 3 sets of each field in my structure table prototypes, some with differing attributes:

![image](https://user-images.githubusercontent.com/18016749/47568629-a0c00900-d8ff-11e8-8829-8b676e34cbb1.png)

**Comment by KevinMcCluney** [comment]
Did you have the check box **Append existing data fields** selected when importing?  I've been able to duplicate the problem only when this is selected.

**Comment by ascended121** [comment]
I did not select append existing data fields and I'm importing into a completely new project. Took a peak at the json and confirmed that the field is listed once with the table definition but results in two fields when imported. 

Is there a way to tell where a field is derived from? Perhaps it would be clearer if fields from the table type were greyed out in the manage fields dialog of the table prototype, so that you could tell which fields belonged to the table type (and couldn't edit them) and which belonged to the table instance? Right now I can't tell who owns each field and so when I go through and try to clean them up I can't tell if I'm deleting the field defined by the table type or extra ones which have ended up in the table instance.

**Comment by KevinMcCluney** [comment]
I've made extensive revisions to the latest version (1.4.42) to address the problems (duplicate fields, missing default fields, disappearing fields).  Testing included repeatedly importing the same file (with all permutations of the "append fields" and "use existing fields" check box selections).

The following scenarios summarize how fields are handled if a table with fields is imported and the table already exists in the database (with or without fields).  **In all cases the table will inherit default fields from its table type definition.**

Scenario 1. Check boxes: [x] replace existing tables   [ ] append existing data fields   [ ] use existing fields.
The table's existing fields are removed.

Scenario 2. Check boxes: [x] replace existing tables   [x] append existing data fields   [ ] use existing fields.
The table's existing fields remain unless there is a duplicate in the import file (the one in the import file overwrites the existing one). 

Scenario 3. Check boxes: [x] replace existing tables   [x] append existing data fields   [x] use existing fields.
The table's existing fields remain unless there is a duplicate in the import file (the existing one is retained an the one in the import file is ignored). 

Regarding the question on highlighting fields in the field editor.  A field is inherited from the table type is a completely new field, belonging to the table that inherited it.  It can be edited and changed in any manner from the original one in the table type.  Inheritance is simply a means of automatically created fields for a table of that type.  So in the field editor all of the fields displayed are owned by the table that spawned the field editor.

**Comment by ascended121** [comment]
In the same way that a table type ensures that all instances of that type have a consistent set of columns defined, I think it would be a useful feature of table types if they ensured that all tables of that type have a consistent set of fields defined. Because of the mutability of these fields on a table-by-table basis, scripts have to be more complex to handle any possible value from any field (since the user may have edited the field definition to an unexpected input type for any particular table).

Also, if the table types are only used during creation of instances of a table type, then it seems like there's opportunity for them to get out of sync with instances of that table. If, for example, several structure tables are created, then a new field is added to the structure table type, and then several more structure tables are created, it sounds like the original set won't have that new field. The user then needs to manually add that new field to the original set of structure tables, introducing opportunity for human error and potentially requiring significant effort (if the number of original tables is large).

Also, as currently implemented, the 'Required' attribute of the fields is not as useful as it could be (in terms of ensuring a value is present) since the user could just delete the field to avoid inputting it for a particular table.

I think fields defined on table types are more useful if its enforced that every table of that type has those fields. I don't think that this restricts the input of table-specific ancillary data (since the user can also add more fields associated with specific instances of that table type, if needed).

**Comment by KevinMcCluney** [comment]
The change to strict inheritance of table type fields is in work (completion date is TBD).  This is a non-trivial update and requires a change to the database schema (i.e., once a database is patched it won't be compatible with older CCDD versions).

**Comment by KevinMcCluney** [comment]
Strict inheritance of default data fields is implemented beginning in version 1.4.47.

**Comment by ascended121** [comment]
This appears to be working, thanks.
