### ISSUE TITLE
Unable to add table to group

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#45]
When using the 'Manage Groups' dialog, I'm able to select a table, select a group, and then click the right arrow to move the table into the group and see that its now listed under that group. When I click the store button no database queries show up in the main window but I'm able to exit the dialog without a warning about unsaved changes. The next time I open the dialog the table I added is not longer present in the group, indicating its not being stored in the database correctly.

**Comment by KevinMcCluney** [comment]
I'm unable to reproduce this behavior.  What version of CCDD are you using?

**Comment by ascended121** [comment]
First observed in 1.4.38 and still occurring in 1.4.40.

As far as I can tell this occurs when one table's name starts with the name of another table which is already part of the group. If I have a table named `my_tbl` part of a group and attempt to add another table called `my_tbl_with_suffix`, I'm unable to. I'm also unable to add `my_tbl` if `my_tbl_with_suffix` is already part of the group. Perhaps this is an issue with any logic which might be attempting to prevent duplicate tables in a group?

**Comment by KevinMcCluney** [comment]
Thanks for the additional information - that made it possible to track down the problem.  The latest version (1.14.41) corrects this.

**Comment by ascended121** [comment]
This appears to be resolved in the version I'm testing in (1.14.48).
