### ISSUE TITLE
Hotkeys in table editing window not responding

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#46]
Each button at the bottom of the table editing window and each dropdown menu along the top has a letter underlined, which implies that they're able to be used by hitting that letter as a hotkey. The only place that this works for me is if I've already opened one of the menus at the top (at which point if I hit one of the selected letters it will execute that command). I'm unable to open any of the menus (ex open File by hitting `F`) nor use any of the buttons along the bottom (ex, Store by hitting `S`) via hotkey. 

As far as I can tell, neither case of the letter works nor is it dependent on what I have selected (ie I'm not editing one of the table fields while attempting to use a hotkey). Hitting ctrl and the letter also doesn't activate the hotkey.

The users guide doesn't appear to have any info on these hotkeys (nothing comes up when I search for hotkey or shortcut) so I'm not sure if this is a bug or if I'm misunderstanding how to use the hotkeys. Observed on 1.4.41 on win10.

**Comment by KevinMcCluney** [comment]
The hotkeys are activated using Alt-<letter> (where <letter> is the underlined letter) for the main menus and buttons (for a sub-menu just the <letter> is needed.  Section 4.4 has information on keyboard navigation and appendix E.1 lists the program-wide hotkeys.

**Comment by ascended121** [comment]
Thanks for pointing that out!
