### ISSUE TITLE
Exception while importing

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#48]
When attempting to import via the CLI, I'm receiving the following exception:

```
An unanticipated error occurred; cause 'null'  Error trace:   
CcddDbCommandHandler: executeDbUpdate() line 123   
CcddDbTableCommandHandler: createTable() line 1171   
CcddFileIOHandler: createImportedTable() line 1482   
CcddFileIOHandler: createTablesFromDefinitions() line 1254   
CcddFileIOHandler: importFile() line 880   
CcddCommandLineHandler: doCommand() line 1060   
CcddCommandLineHandlerCommandHandler: handler() line 385   
CcddCommandLineHandler: parseCommand() line 2119   
CcddCommandLineHandler: parseCommand() line 1985   
CcddMain: parseDbSpecificCommandLineCommands() line 848   
CcddDbControlHandler: complete() line 2657   
CcddBackgroundCommand: done() line 192 
```
The file being imported is successfully imported from the GUI. The following are the last couple lines (out of the ~1600 lines) of the log file:
```
localhost:5432|myproject|myuser|11/08/2018 13:11:40.064|Success|Connected to project 'myproject' as user 'myuser'
localhost:5432|myproject|myuser|11/08/2018 13:11:40.066|Status|PostgreSQL: 9.5  *** JDBC: PostgreSQL 9.4.1207.jre7 (type 4)
localhost:5432|myproject|myuser|11/08/2018 13:11:40.068|Command|SELECT * FROM get_table_members_by_name();
localhost:5432|*none*|myuser|11/08/2018 13:11:40.077|Fail|Cannot load table members; cause 'Connection to server lost'
```
This particular sequence of connecting to the database and then running a command occurs successfully ~100 times earlier in the log file... I'm not sure what causes this one to fail.

The command being run is:
`java -cp "my/Path/CCDD.jar" CCDD.CcddMain -logPath "/my/Path/logs" -create "-name 'myproject' -owner myuser -description 'Project containing interface definitions'" -project myProject -user myuser -import "-fileName '/my/path/to/data/interfaces.json' -replaceExisting true" -shutdown`.

Observed in 1.4.44 on Ubuntu.

**Comment by KevinMcCluney** [comment]
If an imported table's path references a table that doesn't exist and isn't defined in the import file then it creates the missing prototype.  The crash stems from the import attempting to (erroneously) create an undefined prototype more than once.  PostgreSQL returns a null result for this command, and the fall-out is what you see in the log, etc.  The issue will be corrected in the next release.

Releases to Github are held up while the inheritance of table type data fields is worked out (response to issue #44 ).  If you have access to the version on the babelfish repository then the fix will be uploaded by COB today, but be aware that the database schema will need to be patched and there can be issues when importing data fields.  If you don't have babelfish access and need the .jar file now then let me know and I'll e-mail a copy to you.

**Comment by KevinMcCluney** [comment]
With the release of version 1.4.47 the correction of this issue is implemented.

**Comment by SpaceSteve121** [comment]
Thanks, have not been observing this anymore with 1.4.48.
