### ISSUE TITLE
Cannot register database driver

### ISSUE THREAD

**Issue by jongyeob** [nasa/CCDD#5]
Hi,

I got an error, when I create new project BITSE, and then open the project.
I attached a screenshot for this.

I used postgres95 at this time, but have same error on postgres84.

Thanks.

OS: Ubuntu 16.04LTS 64bit
dpkg -l | grep postgres
ii  postgresql                                 9.5+173ubuntu0.1                             all          object-relational SQL database (supported version)
ii  postgresql-9.5                             9.5.10-0ubuntu0.16.04                        amd64        object-relational SQL database, version 9.5 server
ii  postgresql-client-9.5                      9.5.10-0ubuntu0.16.04                        amd64        front-end programs for PostgreSQL 9.5
ii  postgresql-client-common                   173ubuntu0.1                                 all          manager for multiple PostgreSQL client versions
ii  postgresql-common                          173ubuntu0.1                                 all          PostgreSQL database-cluster manager
ii  postgresql-contrib-9.5                     9.5.10-0ubuntu0.16.04                        amd64        additional facilities for PostgreSQL

![2017-12-29 11 14 48](https://user-images.githubusercontent.com/5885949/34427838-ba086974-ec89-11e7-81d0-803bf993c99c.png)

**Comment by KevinMcCluney** [comment]
The event log (the last entry, index 126) indicates that the library file for mXparser is missing.  This library, along with others needed to run the application, is found in the **CCDD_lib** folder.  Make sure you have downloaded this folder into the same folder in which the CCDD.jar file is located.  It's possible given your configuration (for example, 64-bit) that some of the library files in the CCDD_lib folder need to be updated, but try the baseline ones first.  Let me know if this fixes the problem.

**Comment by KevinMcCluney** [comment]
Download the latest CCDD.jar file - the manifest has been updated to include the mXparser library as part of the class path.

**Comment by jongyeob** [comment]
Thanks.

It works.
