### ISSUE TITLE
Type-dependent fields not disabled in custom table type

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#51]
For an instance of the default structure table type, when a non-integer type is selected for a row, the Bit Length and Enumeration are disabled (grayed out) for that row since they're not meaningful for non-integer types. The same behavior is not observed for custom table types with those same conditions, despite using the same input types for each of those columns... they continue to accept user input.

I'm not sure if this is due to the Structure/Command table types being treated specially or if this is a bug. For consistency, it seems that these input types should behave the same for both default and user-defined table types.

**Comment by KevinMcCluney** [comment]
The behavior is constrained based on the table type.  The table's type must be a structure (i.e., have at a minimum a variable name, data type, array size, bit length, enumeration, and rate columns, as defined by their input types) or a command (command name and command code columns) in order for the special handling to be enabled.  Do you have a use case where, say, a bit length and a data type column outside of a structure is needed (or something similar)?  If so, I'll look into relaxing the constraints.  I'm uncertain if the same behaviors can work for all cases where the table type isn't a structure (for example, an array size column in a table with no data type column) - these are very entwined.

**Comment by ascended121** [comment]
I've defined a new table type for use in storing arbitrary CFE app tables (which are data structures, and so share many of the same columns as structure tables, but are not telemetered, and thus do not need a rate column). It looks like the lack of a rate column might be what's preventing my custom table type from having the fields disabled as expected.

It seems like each disableable field type (Bit Length, Enumeration, Rate) has a dependency on the 'Primitive and Structure' column existing, which the current constraints capture. But the current constraints also make the disableable fields depend on each-other's existence, which I'm not sure is necessary for the behavior to make sense.

**Comment by KevinMcCluney** [comment]
CCDD version 2 (in the new CCDD 2 branch) removes the requirement for a structure table to include a rate column.
