### ISSUE TITLE
Imported table not matching json file

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#52]
I'm seeing an issue where the table definition imported by CCDD does not match the table definition in the json file being imported. The json file was created via export from CCDD. This issue is reproduceable through both the CLI and GUI. The log files contains no 'Fail' entries and contains a successful import entry at the end.

As far as I've noticed, this is only affecting one table hierarchy (root and children) in my project right now. I'm not sure what details are relevant here, so here's a description of the table hierarchy in question:

The root table contains several elements, all of which are child tables (no base datatypes). The child tables each have several elements, all of which have descriptions, several of which have units defined, and several of which have enumerations (defined as macros). I see all of these attributes in the exported json file, however when my coworker imports the file, CCDD has only imported the name, data type, and array size of the elements of the each of the tables (root and children). Coincidentally the missing fields are ones that I added recently (which is how this was discovered), but I can't find anything about the contents of these fields that would cause this issue. 

Observed on CCDD 1.4.49 on Windows, Ubuntu, and OSX.

**Comment by KevinMcCluney** [comment]
I set up a table hierarchy similar to what you describe and it's importing correctly, so I need more information in order to proceed:

1) Did you inspect the JSON file directly to see if the the missing information is in the file?  If, when exporting, only the child table _prototypes_ were selected (along with the root table), but not the child tables _instances_, then the behavior you see can be reproduced (and is what would be expected).

Assuming the export file is in order:

2) Can you attempt to import the file into a new (empty) project and see if the behavior is the same?  If it imports correctly it points to an issue with the project or some interaction with the existing tables.

3) Can you attach the JSON export file (or files) and the event log (where the import is incomplete)?

**Comment by ascended121** [comment]
The export was created using the 'All Tables' group. I am seeing all the information that was in CCDD reflected in the json file, so I believe the export is working as intended.

I observe the same behavior with a new project. Will have to coordinate sending the JSON file/log file offline. I'll contact you. Thanks!

**Comment by KevinMcCluney** [comment]
Version 1.4.52 has been uploaded.  It has a major change that affects pasting data into a table (which is used by the import operation).  Preliminary testing appears to have corrected that issue.  The export file may have some of the information (such as the descriptions) incorrect.  This may be another issue, which I'm checking into.

**Comment by ascended121** [comment]
The original file (exported from 1.4.49) I sent you still does not import in 1.4.52, so this fix does not appear to have fixed whatever's causing that. Exporting the database again (from 1.4.52) and then importing that json file appears to work as intended, so it appears that at least 1.4.52 exports can be imported by 1.4.52.

Its difficult to determine if there's differences in the table definitions (which might be attributed to the ongoing export issue you mentioned) because the order that tables are exported in appears to have changed, which is befuddling a simple diff. I'll need to take some more time check the definitions to ensure that the descriptions are correct. Will let you know if I find any issues with this export.

**Comment by KevinMcCluney** [comment]
The original JSON file has incorrect information.  For example, look at the descriptions for array variable **qi2b** in table AC_AD_Tlm: AC_GenAD.GenAD.  Variable qi2b[0] has the description that should go with array variable wi2b.  Variable qi2b[1] has the descirption that should be with attSelectFlag.  Variable qi2b[2] has the description that should be with rateSelectFlag.  I've tested the export with the file you sent (after correcting the descriptions noted above) and it exported correctly.  I imported the JSON file created into a new project using version 1.4.52 and it imported correctly.  You need to recreate the JSON file (with any corrections made).
The JSON parser seems to randomize the order of the output to some degree - I have no control over it.

**Comment by KevinMcCluney** [comment]
When exporting tables via the command line _export_ command the list of tables created for the 'All tables' group is missing the non-root prototype tables.  Version 1.4.57 (to be uploaded today) corrects this.

**Comment by KevinMcCluney** [comment]
Version 1.4.72 addresses the issue where the JSON output order is more or less random.  The order is now consistent from export to export.  The tables appear in alphanumeric order.  Each table's information is in a specific order.  Non-table information (e.g., macros, data types, etc.) appear after all of the tables, and the order of this information is consistent as well.

**Comment by ascended121** [comment]
After upgrading, unable to use my current project (because when I try to open any table it says its missing) and when I try to import a recent export of my project I get:

```Cannot parse import file path/to/file; cause 'null'```

**Comment by ascended121** [comment]
Actually, that import error was my fault... file was empty due to a previous error. When importing, now getting: 
![image](https://user-images.githubusercontent.com/18016749/52441831-ba244400-2aef-11e9-8fd7-6ab01dd52416.png)

If I do manage to get my database imported, then when access tables I get the following status 
```Cannot load table 'myTable'; cause 'Table doesn't exist'```
for all tables.

**Comment by KevinMcCluney** [comment]
Version 1.4.75 should address the issues you're seeing.

**Comment by BaldBeacon** [comment]
JSON objects are intrinsically unordered since they are hashed (which is where the "randomness" comes from). Ultimately, due to the hashed nature of JSON this means diffing a file should not be the go to when comparing JSON files. The appropriate way to compare JSON is with an online [jsondiff](http://jsondiff.com/) tool or by using command line tool like [jq](https://stedolan.github.io/jq/). This is all detailed in the [JSON spec](https://www.json.org/).

**Comment by KevinMcCluney** [comment]
I don't disagree.  Keeping the order repeatable, however, does make reading the file easier (eyeballing, that is).
