### ISSUE TITLE
Table not removed from group on deletion

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#53]
When deleting a table CCDD does not remove the table from any groups of which it was a member, requiring the user to then open the group editor to manually remove it. Failing to do so will cause errors (due to missing tables) when attempting to use that group with scripts in the future.

It would be helpful for CCDD to automatically remove a deleted table from any groups of which it was a part.

**Comment by KevinMcCluney** [comment]
I'm unable to duplicate the issue.  I tried assigning a prototype to a group and an instance to a group. I deleted the prototype and the group was updated correctly; I deleted the instance and the group was updated correctly.  Please send me information on what type of table you deleted (prototype or instance).  If you're deleting a prototype you should get a logged event similar to the following (replace __del_ with the name of the table you're deleting):

DROP TABLE IF EXISTS _del CASCADE; DELETE FROM __values WHERE table_path ~ E'^_del$' OR table_path ~ E'^_del,' OR table_path ~ E',_del\\.'; DELETE FROM __links WHERE member_variables ~ E'^_del$' OR member_variables ~ E'^_del,' OR member_variables ~ E',_del\\.'; DELETE FROM __tlm_scheduler WHERE member_variable ~ E'^\\d+\\.\\d+\\\\_del$' OR member_variable ~ E'^\\d+\\.\\d+\\\\_del,' OR member_variable ~ E',_del\\.'; **DELETE FROM __groups WHERE member_tables ~ E'^_del$' OR member_tables ~ E'^_del,' OR member_tables ~ E',_del\\.';** DELETE FROM __fields WHERE owner_name ~ E'^_del$' OR owner_name ~ E'^_del,' OR owner_name ~ E',_del\\.'; DELETE FROM __orders WHERE table_path ~ E'^_del$' OR table_path ~ E'^_del,' OR table_path ~ E',_del\\.'; UPDATE __associations SET member_tables = regexp_replace(member_tables, E'(?:(?:^|(?:[a-zA-Z0-9_,\\.\\[\\]]+,))_del(?:(?:,|\\.)[a-zA-Z0-9_,\\.\\[\\]]+)?;\\n|;\\n(?:^| \+ |[a-zA-Z0-9_,\\.\\[\\]]+,)?_del(?:(?:,|\\.)[a-zA-Z0-9_,\\.\\[\\]]+)?)', E'', 'g'); UPDATE __associations SET member_tables = '' WHERE member_tables ~ E'^(?:[a-zA-Z0-9_,\\.\\[\\]]+,)?_del(?:(?:,|\\.)[a-zA-Z0-9_,\\.\\[\\]]+)?$';

Are you seeing the portion above in **bold**?  If not, please send the log entry you do get.

If you're deleting an instance (by deleting a structure variable) you should see a logged event similar to the following (replace __del_ with the name of the table you're deleting):

DELETE FROM __fields WHERE owner_name = 'a_ver2'; INSERT INTO __fields VALUES ('a_ver2', 'Message ID', '', 20, 'Message name & ID', false, 'Roots only', '0x0ef6', true), ('a_ver2', 'System', '', 15, 'Text', false, 'All tables', '', true); DELETE FROM __values WHERE table_path = 'a_ver2' AND column_name = ''; DELETE FROM __orders WHERE user_name = 'rmcclune' AND table_path = 'a_ver2'; INSERT INTO __orders (user_name, table_path, column_order) VALUES ('rmcclune', 'a_ver2', '0:1:2:3:4:5:6:7:8:9:10:11:12:13:14'); DELETE FROM a_ver2 WHERE _key_ = 252; DELETE FROM __values WHERE table_path ~ E'^a_ver2,_del\\.delVar(?:,|:|$)' OR table_path ~ E'^.+,a_ver2\\.[^,]*,_del\\.delVar(?:,|:|$)'; UPDATE a_str_cpy SET variable_reference = '' WHERE variable_reference ~ E'(?:^|.+,)a_ver2,delVar(?:,|$)'; UPDATE __values SET value = '' WHERE table_path ~ E'^.+,a_str_cpy\\..*$' AND column_name = 'Variable Reference' AND value ~ E'(?:^|.+,)a_ver2,delVar(?:,|$)'; UPDATE a_struct_copy SET variable_reference = '' WHERE variable_reference ~ E'(?:^|.+,)a_ver2,delVar(?:,|$)'; UPDATE __values SET value = '' WHERE table_path ~ E'^.+,a_struct_copy\\..*$' AND column_name = 'Variable Reference' AND value ~ E'(?:^|.+,)a_ver2,delVar(?:,|$)'; UPDATE imp_test SET variable_reference = '' WHERE variable_reference ~ E'(?:^|.+,)a_ver2,delVar(?:,|$)'; **DELETE FROM __groups WHERE member_tables ~ E'^a_ver2,_del\\.delVar(?:,|$)' OR member_tables ~ E'^.+,a_ver2\\.[^,]*,_del\\.delVar(?:,|$)';** DELETE FROM __fields WHERE owner_name ~ E'^a_ver2,_del\\.delVar(?:,|$)' OR owner_name ~ E'^.+,a_ver2\\.[^,]*,_del\\.delVar(?:,|$)'; UPDATE __fields SET field_value = '' WHERE field_type = E'Variable reference' AND field_value ~ E'(?:^|.+,)a_ver2,delVar(?:,|$)'; DELETE FROM __orders WHERE table_path ~ E'^a_ver2,_del\\.delVar(?:,|$)' OR table_path ~ E'^.+,a_ver2\\.[^,]*,_del\\.delVar(?:,|$)'; UPDATE __associations SET member_tables = regexp_replace(member_tables, E'^a_ver2,_del\\.delVar(?:,[a-zA-Z0-9_,\\.\\[\\]]+)?', E'', 'ng'); UPDATE __associations SET member_tables = regexp_replace(member_tables, E'^.+,a_ver2\\.[^,]*,_del\\.delVar(?:,[a-zA-Z0-9_,\\.\\[\\]]+)?', E'', 'ng'); UPDATE __associations SET member_tables = regexp_replace(member_tables, E'^;\\n', E'', 'ng'); UPDATE __associations SET member_tables = regexp_replace(member_tables, E';\\n$', E'', 'ng'); DELETE FROM __links WHERE member_variables ~ E'^a_ver2,_del\\.delVar(?:,|:|$)'; DELETE FROM __links WHERE member_variables ~ E'^.+,a_ver2\\.[^,]*,_del\\.delVar(?:,|:|$)'; DELETE FROM __tlm_scheduler WHERE member_variable ~ E'^.*\\\\a_ver2,_del\\.delVar(?:,|:|$)'; DELETE FROM __tlm_scheduler WHERE member_variable ~ E'^.*\\\\.+,a_ver2\\.[^,]*,_del\\.delVar(?:,|:|$)';

Are you seeing the portion above in **bold**?  If not, please send the log entry you do get.

**Comment by ascended121** [comment]
Issue appears to have been caused by child tables in the group definitions which did not have a path assigned to them. Its unclear how the groups ended up with child takes which were missing paths, but removing and re-adding those tables them resolved the issue.

Also, Kevin noted that using the Project > Verify command should detect this issue in the future.
