### ISSUE TITLE
Macro definitions cleared when running script from CLI

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#54]
When running a script via the CLI, I'm observing that all macro definitions are cleared. 

After importing a project which has macro definitions, I'm able to run a script (through the GUI) and generate the artifact without issue. If I close CCDD and re-run that same script via the CLI, when I reopen CCDD the macro definitions are no longer present. The clearing appears to take place before the script is run because scripts which depend on those macros will error.

So far this has been observed on OSX and Linux with v1.4.55. Can provide logs if that's helpful.

**Comment by KevinMcCluney** [comment]
The problem isn't with the scripts - the macro clearing actually occurs during import, though it isn't obvious.  This is fallout from a recent upgrade (last week) that allows imported macro values to replace existing ones (a useful feature requested by another group).  The macros are imported into memory correctly, and show up in the macro editor; however, they aren't getting stored to the database.  So when the program is exited the macros are lost, and hence a subsequent execution (as when you run the scripts via the command line) won't find any macro definitions.  The correction is in version 1.4.57, to be upload later today.
