### ISSUE TITLE
Changing applicability of field deletes all values

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#55]
When changing the applicability of a table field, all values from all existing instances of that field are cleared. This is undesirable and causes unnecessary loss of data.

For example, when a field with scope 'All Tables' is changed to 'Roots Only', the field is (properly) no longer displayed on child tables but the field is also cleared for all root tables, requiring the user to re-enter the values for the root tables (whose field hasn't changed). 

The same happens in the opposite direction. For example, when a field with scope 'Roots Only' is changed to 'All Tables' the field is (properly) created for all child tables and is blank (because it previously didn't exist), however the field is now also blank for all root tables, even though they didn't change.

Observed on 1.4.62.

**Comment by KevinMcCluney** [comment]
Overwriting of field values is determined by the menu selection in the table type editor (Field | Overwrite values...).  The selections are 'All' (the default), 'If same', 'If empty', and 'None' - see section 4.9.3.10.4.3
 in the user's guide for an explanation for these selections.  To prevent overwriting in the case you mentioned, use 'None'.

**Comment by SpaceSteve121** [comment]
Thanks for the reference... hadn't see that option. In my experience (with 1.4.65) the default does not appear to be 'None' as indicated in the users guide. In all my existing projects and for new projects I'm seeing it set to 'All'.

**Comment by ascended121** [comment]
Thanks for the reference... hadn't see that option. In my experience (with 1.4.65) the default does not appear to be 'None' as indicated in the users guide. In all my existing projects and for new projects I'm seeing it set to 'All'.
