### ISSUE TITLE
Version number in export

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#56]
Currently it does not appear that CCDD includes the version from which an export was generated in the resulting file. It would be helpful for debugging changes to the export format (like the ones which changed the ordering with version 1.4.75) on multiple users setups (who are on various versions, depending on when they last pulled) to be able to tell what version the export was derived from. Could just be part of the existing File Description elements.

Thanks

**Comment by KevinMcCluney** [comment]
Version 1.4.78 adds the CCDD version information to CSV and JSON exports (EDS and XTCE already had it).
