### ISSUE TITLE
Project name case-sensitive in delete subcommand

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#57]
CCDD appears to require an all-lowercase version of the project name when using the delete subcommand, as demonstrated below.
```
>java -cp "C:\Programs\CCDD\CCDD.jar" CCDD.CcddMain -logPath "C:\Programs\CCDD\logs"  -create "-name 'TestCapitals'" -shutdown
>java -cp "C:\Programs\CCDD\CCDD.jar" CCDD.CcddMain -logPath "C:\Programs\CCDD\logs"  -delete "-name 'TestCapitals'" -shutdown
Error: Delete project failed; project 'TestCapitals' does not exist
>java -cp "C:\Programs\CCDD\CCDD.jar" CCDD.CcddMain -logPath "C:\Programs\CCDD\logs"  -delete "-name 'testcapitals'" -shutdown
```
It looks like CCDD may be expecting the database name, rather than the project name, which appears to always be lowercase.

Also, the failed command in the sequence above is not reflected in the log file generated from that session... I only see command and success entries.

**Comment by ascended121** [comment]
Its worth noting that the case-sensitivity is called out in the user's guide with the following verbage `Project database name.  The project’s database name is case sensitive`. It appears, in terms of the create command, that it's lowercased before being used as the database name whereas in the delete command it is not.

Since the exact same phrasing is used with both the create command and the delete command, that implies (to me at least) that if I put the same thing in for both commands it should work the same.

**Comment by KevinMcCluney** [comment]
There's an error in the code - it should behave as described in the guide.  I'll upload a correction tomorrow.

**Comment by KevinMcCluney** [comment]
Version 1.4.81 corrects this issue.
