### ISSUE TITLE
All javadoc files modified in recent commits

### ISSUE THREAD

**Issue by SpaceSteve121** [nasa/CCDD#60]
In some recent commits it appears that every JavaDoc file has changes because the timestamps within them are updated when they're regenerated. This might not be desirable because it makes it harder to identify real changes in the code while examining a particular commit (ex, commit 173775acffc has 691 changes files, almost all of which appear to be JavaDoc timestamp changes).

It looks like JavaDoc supports a `-notimestamp` argument that would omit that timestamp, which should result in only the files containing actual changes containing diffs, making it easier to find real changes in the commits. 

I found reference to this option here: https://stackoverflow.com/questions/5613847/remove-the-comment-generated-by-javadoc-on-date-time-in-generated-javadoc

**Comment by KevinMcCluney** [comment]
Added the -notimestamp option to the Javadoc build in version 1.4.97.
