### ISSUE TITLE
File description in JSON export causes merge conflicts

### ISSUE THREAD

**Issue by SpaceSteve121** [nasa/CCDD#61]
The JSON file exported by CCDD contains a `File Description` field which contains a timestamp, username, and project name. The values of these fields tends to change within a distributed development environment and is flagged as a conflict within this file each time it's part of a merge  (requiring the developer to manually resolve the differences in the File Description, even though they don't affect the contents/import of this file).

It would be useful if CCDD provided an option (accessible via at least the CLI) to omit the File Description field from the export.

**Comment by KevinMcCluney** [comment]
Version 1.5.4 has a new export command option, includeBuildInformation, which defaults to ‘true’.  Set it to false to exclude the file description (this does the same for the other export file types as well).

**Comment by SpaceSteve121** [comment]
In 1.5.4, the option exists (it throws an error if I specify it as something other than true or false), but does not appear to be working. For an export subcommand as follows:
```
 -export "-filePath path/to/output.json -format json -includeBuildInformation false -tablePaths 'Group:All tables' -includeProjectFields true -singleFile true -overwriteFile true -includeGroups true"
```
I'm still seeing a `File Description` field in the output.

**Comment by KevinMcCluney** [comment]
I found the problem - it's corrected.  I elected to keep the version number the same.

**Comment by SpaceSteve121** [comment]
Thanks, looks like its working!
