### ISSUE TITLE
CCDD returns success when failing to parse import file

### ISSUE THREAD

**Issue by SpaceSteve121** [nasa/CCDD#62]
When attempting to import an invalidly-formatted json file, I'm getting the following from CCDD:

```
File Warning : Cannot parse import file 'C:\path\to\my\file.json'; cause 'null'
```

which is expected, however CCDD exits with a return code of 0 (success), which makes it difficult to detect and respond to the error in scripts.

**Comment by KevinMcCluney** [comment]
This is corrected in version 1.5.6.  The EDS and XTCE imports had a similar issue which is also corrected.
