### ISSUE TITLE
CCDD will not start if directory specified by logpath argument doesn't exist

### ISSUE THREAD

**Issue by SpaceSteve121** [nasa/CCDD#64]
When attempting to start CCDD with the logpath CLI argument specifying a directory that doesn't exist, CCDD with emit the following error and fail to open:

`Log Error : Cannot create event log file`

I think more user-friendly behavior would be to create the folder if it doesn't exist (or perhaps provide a CLI argument that tells it to create if missing, if that behavior is undesirable for some set of users) and only fail if it cannot create that folder.

Observed on version 1.5.24.

**Comment by KevinMcCluney** [comment]
In version 1.5.25 (and 2.0.0) the folder specified by the -logPath command is created if it doesn't exist (a message is sent to the command line indicating this).  If the folder cannot be created then the 'Cannot create event log file' warning is displayed.  In any case program execution continues.

Your description above indicates that the program failed to open when the log couldn't be created - if this is the case then there's some sort of bug which I can't reproduce.
