### ISSUE TITLE
Importing XTCE Issues

### ISSUE THREAD

**Issue by bbrisnehan** [nasa/CCDD#66]
I am trying to import command and telemetry into CCDD from an XTCE file.  I have successfully  validated the file using the XTCE 1.1 schema ([XTCE 1.1](https://www.omg.org/spec/XTCE/20061101/06-11-06.xsd)).  The following XTCE imports without error (though not the same command specifications):

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SpaceSystem xmlns="http://www.omg.org/space/xtce" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Trial" shortDescription="Trial" xsi:schemaLocation="http://www.omg.org/spec/XTCE/20061101 06-11-06.xsd">
    <AncillaryDataSet>
        <AncillaryData name="XML: Application ID">applicationID</AncillaryData>
        <AncillaryData name="XML: Function Code">functionCode</AncillaryData>
    </AncillaryDataSet>
    <Header classification="DOMAIN" date="Tue Aug 13 13:34:26 MDT 2019" validationStatus="Working" version="1.0">
        <AuthorSet>
            <Author>e392889</Author>
        </AuthorSet>
        <NoteSet>
            <Note>CCDD Version: 1.5.27 (7-16-2019)</Note>
            <Note>Date: Tue Aug 13 13:34:26 MDT 2019</Note>
            <Note>Project: Trial</Note>
            <Note>Host: localhost:5432</Note>
            <Note>Endianess: big</Note>
        </NoteSet>
    </Header>
    <SpaceSystem name="CFS_CMD" shortDescription="cFS Command">
        <Header classification="INTERFACE" validationStatus="Working" version="1.0"/>
        <CommandMetaData>
            <ParameterTypeSet>
                <IntegerParameterType name="UINT08Type" initialValue="0" sizeInBits="8" signed="false">
                    <UnitSet />
                    <IntegerDataEncoding encoding="unsigned" sizeInBits="8" bitOrder="leastSignificantBitFirst" />
                </IntegerParameterType>
                <IntegerParameterType name="TestDynamicValueType" initialValue="200" sizeInBits="8" signed="false">
                    <UnitSet/>
                    <IntegerDataEncoding encoding="unsigned" sizeInBits="8" bitOrder="leastSignificantBitFirst"/>
                </IntegerParameterType>
                <ArrayParameterType name="Array_UINT08Type" numberOfDimensions="1" arrayTypeRef="UINT08Type" />
            </ParameterTypeSet>
            <ParameterSet>
                <Parameter name="TestDynamicValue"   parameterTypeRef="TestDynamicValueType" shortDescription="Test Dynamic Value"/>
            </ParameterSet>
            <ArgumentTypeSet>
                <IntegerArgumentType name="UINT08Type" sizeInBits="8" signed="false">
                    <UnitSet />
                    <IntegerDataEncoding encoding="unsigned" sizeInBits="8" bitOrder="leastSignificantBitFirst" />
                </IntegerArgumentType>
                <ArrayArgumentType name="Array_UINT08Type" numberOfDimensions="1" arrayTypeRef="UINT08Type" />
            </ArgumentTypeSet>
            <MetaCommandSet>
                
                <MetaCommand name="TestCommand1">
                    <LongDescription>Example Test Command 1</LongDescription>
                    <CommandContainer name="TestCommand1Container">
                        <LongDescription>Example Test Command Container</LongDescription>
                        <EntryList/>
                        <BaseContainer containerRef="TestContainer">
                            <RestrictionCriteria>
                                <ComparisonList>
                                    <Comparison value="0" parameterRef="TestParameter1"/>
                                    <Comparison value="1" parameterRef="TestParameter2"/>
                                </ComparisonList>
                            </RestrictionCriteria>
                        </BaseContainer>
                    </CommandContainer>
                </MetaCommand>
                
                <MetaCommand name="TestCommand2">
                    <LongDescription>Example Test Command 2</LongDescription>
                    
                    <BaseMetaCommand metaCommandRef="TestCommand1">
                        <ArgumentAssignmentList/>
                    </BaseMetaCommand>
                    <ArgumentList>
                        <Argument name="TestArgument1" argumentTypeRef="UINT08Type"/>
                        <Argument name="TestArgument2" argumentTypeRef="UINT08Type"/>
                    </ArgumentList>
                    <CommandContainer name="C_CommandHeader">
                        <EntryList>
                            <ArgumentRefEntry argumentRef="TestArgument1"/>
                            <ArgumentRefEntry argumentRef="TestArgument2"/>
                        </EntryList>
                        <BaseContainer containerRef="TestCommand1Container"/>
                    </CommandContainer>
                </MetaCommand>
                <MetaCommand name="TestCommand3">
                    <LongDescription>Example Test Command 3</LongDescription>
                    <BaseMetaCommand metaCommandRef="TestCommand2">
                        <ArgumentAssignmentList>
                            <ArgumentAssignment argumentName="TestArgument3" argumentValue="4"/>
                        </ArgumentAssignmentList>
                    </BaseMetaCommand>
                    <ArgumentList>
                        <Argument name="TestArgument4" argumentTypeRef="UINT08Type" shortDescription="Short Description 1"/>
                        <Argument name="TestArgument5" argumentTypeRef="Array_UINT08Type" shortDescription="Short Description 2"/>
                        <Argument name="TestArgument6" argumentTypeRef="UINT08Type" shortDescription="Short Description 3"/>
                        <Argument name="TestArgument7" argumentTypeRef="UINT08Type" shortDescription="Short Description 4"/>
                        <Argument name="TestArgument8" argumentTypeRef="Array_UINT08Type" shortDescription="Short Description 5"/>
                    </ArgumentList>
                    <CommandContainer name="TestCommand3Container">
                        <EntryList>
                            <ArgumentRefEntry argumentRef="TestArgument4"/>
                            <ArrayArgumentRefEntry parameterRef="TestArgument5">
                                <DimensionList>
                                    <Dimension>
                                        <StartingIndex>
                                            <FixedValue>0</FixedValue>
                                        </StartingIndex>
                                        <EndingIndex>
                                            <FixedValue>2</FixedValue>
                                        </EndingIndex>
                                    </Dimension>
                                </DimensionList>
                            </ArrayArgumentRefEntry>
                            <ArgumentRefEntry argumentRef="TestArgument6"/>
                            <ContainerRefEntry containerRef="TestCommand3ContainerRef"/>
                            <ArrayArgumentRefEntry parameterRef="TestArgument8">
                                <DimensionList>
                                    <Dimension>
                                        <StartingIndex>
                                            <FixedValue>0</FixedValue>
                                        </StartingIndex>
                                        <EndingIndex>
                                            
                                            <FixedValue>2</FixedValue>
                                        </EndingIndex>
                                    </Dimension>
                                </DimensionList>
                            </ArrayArgumentRefEntry>
                        </EntryList>
                        <BaseContainer containerRef="TestCommand3Header">
                            <RestrictionCriteria>
                                <ComparisonList>
                                    <Comparison value="1" parameterRef="TestComparison1"/>
                                    <Comparison value="2" parameterRef="TestComparison2"/>
                                    <Comparison value="3" parameterRef="TestComparison3"/>
                                    <Comparison value="4" parameterRef="TestComparison4"/>
                                </ComparisonList>
                            </RestrictionCriteria>
                        </BaseContainer>
                    </CommandContainer>
                </MetaCommand>
            </MetaCommandSet>
        </CommandMetaData>
    </SpaceSystem>
</SpaceSystem>`

This XTCE imports with errors:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SpaceSystem xmlns="http://www.omg.org/space/xtce" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Trial" shortDescription="Trial" xsi:schemaLocation="http://www.omg.org/spec/XTCE/20061101 06-11-06.xsd">
    <AncillaryDataSet>
        <AncillaryData name="XML: Application ID">applicationID</AncillaryData>
        <AncillaryData name="XML: Function Code">functionCode</AncillaryData>
    </AncillaryDataSet>
    <Header classification="DOMAIN" date="Tue Aug 13 13:34:26 MDT 2019" validationStatus="Working" version="1.0">
        <AuthorSet>
            <Author>e392889</Author>
        </AuthorSet>
        <NoteSet>
            <Note>CCDD Version: 1.5.27 (7-16-2019)</Note>
            <Note>Date: Tue Aug 13 13:34:26 MDT 2019</Note>
            <Note>Project: Trial</Note>
            <Note>Host: localhost:5432</Note>
            <Note>Endianess: big</Note>
        </NoteSet>
    </Header>
    <SpaceSystem name="CFS_CMD" shortDescription="cFS Command">
        <Header classification="INTERFACE" validationStatus="Working" version="1.0"/>
        <CommandMetaData>
            <ParameterTypeSet>
                <IntegerParameterType name="UINT08Type" initialValue="0" sizeInBits="8" signed="false">
                    <UnitSet />
                    <IntegerDataEncoding encoding="unsigned" sizeInBits="8" bitOrder="leastSignificantBitFirst" />
                </IntegerParameterType>
                <IntegerParameterType name="TestDynamicValueType" initialValue="200" sizeInBits="8" signed="false">
                    <UnitSet/>
                    <IntegerDataEncoding encoding="unsigned" sizeInBits="8" bitOrder="leastSignificantBitFirst"/>
                </IntegerParameterType>
                <ArrayParameterType name="Array_UINT08Type" numberOfDimensions="1" arrayTypeRef="UINT08Type" />
            </ParameterTypeSet>
            <ParameterSet>
                <Parameter name="TestDynamicValue"   parameterTypeRef="TestDynamicValueType" shortDescription="Test Dynamic Value"/>
            </ParameterSet>
            <ArgumentTypeSet>
                <IntegerArgumentType name="UINT08Type" sizeInBits="8" signed="false">
                    <UnitSet />
                    <IntegerDataEncoding encoding="unsigned" sizeInBits="8" bitOrder="leastSignificantBitFirst" />
                </IntegerArgumentType>
                <ArrayArgumentType name="Array_UINT08Type" numberOfDimensions="1" arrayTypeRef="UINT08Type" />
            </ArgumentTypeSet>
            <MetaCommandSet>
                <MetaCommand name="TestCommand1" abstract="true">
                
                    <LongDescription>Example Test Command 1</LongDescription>
                    <CommandContainer name="TestCommand1Container">
                        <LongDescription>Example Test Command Container</LongDescription>
                        <EntryList/>
                        <BaseContainer containerRef="TestContainer">
                            <RestrictionCriteria>
                                <ComparisonList>
                                    <Comparison value="0" parameterRef="TestParameter1"/>
                                    <Comparison value="1" parameterRef="TestParameter2"/>
                                </ComparisonList>
                            </RestrictionCriteria>
                        </BaseContainer>
                    </CommandContainer>
                </MetaCommand>
                <MetaCommand name="TestCommand2" abstract="true">
                
                    <LongDescription>Example Test Command 2</LongDescription>
                    <BaseMetaCommand metaCommandRef="TestCommand1"/>
                    
                    <ArgumentList>
                        <Argument name="TestArgument1" argumentTypeRef="UINT08Type"/>
                        <Argument name="TestArgument2" argumentTypeRef="UINT08Type"/>
                    </ArgumentList>
                    <CommandContainer name="C_CommandHeader">
                        <EntryList>
                            <ArgumentRefEntry argumentRef="TestArgument1"/>
                            <ArgumentRefEntry argumentRef="TestArgument2"/>
                        </EntryList>
                        <BaseContainer containerRef="TestCommand1Container"/>
                    </CommandContainer>
                </MetaCommand>
                <MetaCommand name="TestCommand3">
                    <LongDescription>Example Test Command 3</LongDescription>
                    <BaseMetaCommand metaCommandRef="TestCommand2">
                        <ArgumentAssignmentList>
                            <ArgumentAssignment argumentName="TestArgument3" argumentValue="4"/>
                        </ArgumentAssignmentList>
                    </BaseMetaCommand>
                    <ArgumentList>
                        <Argument name="TestArgument4" argumentTypeRef="UINT08Type" shortDescription="Short Description 1"/>
                        <Argument name="TestArgument5" argumentTypeRef="Array_UINT08Type" shortDescription="Short Description 2"/>
                        <Argument name="TestArgument6" argumentTypeRef="UINT08Type" shortDescription="Short Description 3"/>
                        <Argument name="TestArgument7" argumentTypeRef="UINT08Type" shortDescription="Short Description 4"/>
                        <Argument name="TestArgument8" argumentTypeRef="Array_UINT08Type" shortDescription="Short Description 5"/>
                    </ArgumentList>
                    <CommandContainer name="TestCommand3Container">
                        <EntryList>
                            <ArgumentRefEntry argumentRef="TestArgument4"/>
                            <ArrayArgumentRefEntry parameterRef="TestArgument5">
                                <DimensionList>
                                    <Dimension>
                                        <StartingIndex>
                                            <FixedValue>0</FixedValue>
                                        </StartingIndex>
                                        <EndingIndex>
                                            <FixedValue>2</FixedValue>
                                        </EndingIndex>
                                    </Dimension>
                                </DimensionList>
                            </ArrayArgumentRefEntry>
                            <ArgumentRefEntry argumentRef="TestArgument6"/>
                            <ContainerRefEntry containerRef="TestCommand3ContainerRef"/>
                            <ArrayArgumentRefEntry parameterRef="TestArgument8">
                                <DimensionList>
                                    <Dimension>
                                        <StartingIndex>
                                            <FixedValue>0</FixedValue>
                                        </StartingIndex>
                                        <EndingIndex>
                                            <DynamicValue>
                                                <ParameterInstanceRef parameterRef="TestDynamicValue"/>
                                                <LinearAdjustment intercept="-1"/>
                                            </DynamicValue>
                                            
                                        </EndingIndex>
                                    </Dimension>
                                </DimensionList>
                            </ArrayArgumentRefEntry>
                        </EntryList>
                        <BaseContainer containerRef="TestCommand3Header">
                            <RestrictionCriteria>
                                <ComparisonList>
                                    <Comparison value="1" parameterRef="TestComparison1"/>
                                    <Comparison value="2" parameterRef="TestComparison2"/>
                                    <Comparison value="3" parameterRef="TestComparison3"/>
                                    <Comparison value="4" parameterRef="TestComparison4"/>
                                </ComparisonList>
                            </RestrictionCriteria>
                        </BaseContainer>
                    </CommandContainer>
                </MetaCommand>
            </MetaCommandSet>
        </CommandMetaData>
    </SpaceSystem>
</SpaceSystem>`

When running CCDD Version Version 1.5.27:

1. When abstract is implemented, it returns:

*Duplicate Table(s)*

Ignored the following duplicate table definitioin(s): CFS_CMD (file: error.xtce)

If both abstract commands in the file include the token then it brings in TestArgument1 and TestArgument2.

2. When BaseMetaCommand is implemented without an empty 'ArgumentAssignmentList' underneath, it returns:

*CCDD Error*

An unanticipated error occurred; cause 'null'

Error trace:
  CcddXTCEHanler: importCommandTable() line 1498
  CcddXTCEHanler: unbuildSpaceSystems() line 1146
  CcddXTCEHanler: importFromFile() line 687
  CcddFileIOHandler: importFile() line 1044
  CcddFileIOHandler: execute() line 846
  CcddBackgroundCommand: doInBackground() line 144
  CcddBackgroundCommand: doInBackground() line 1
  
The implementation with an empty 'ArgumentAssignmentList' underneath (while working with the import tool) appears to fail validation when checked against the XTCE 1.1 schema.
  
  
3. When the DynamicValue is implemented, it returns:

*CCDD Error*

An unanticipated error occurred; cause 'null'

Error trace:
  CcddXTCEHanler: processArgumentReference() line 2367
  CcddXTCEHanler: importCommandTable() line 1606
  CcddXTCEHanler: unbuildSpaceSystems() line 1146
  CcddFileIOHandler: importFromFile() line 687
  CcddFileIOHandler: importFile() line 1044
  CcddFileIOHandler: execute() line 846
  CcddBackgroundCommand: doInBackground() line 144
  CcddBackgroundCommand: doInBackground() line 1

**Comment by bbrisnehan** [comment]
I've asked around and it sounds like the 'abstract' was used in MetaCommands in an effort to allow inheritance (without direct use).  From your response it sounds like those should be placed in SequenceContainers.

For DynamicValue, as one example, each mission can change the length of time field (CCSDS_TIME_SIZE) in the CCSDS telemetry secondary header.  Rather than hardcode it, we setup a parameter to use as a reference for the ending index for all telemetry.

**Comment by KevinMcCluney** [comment]
In the example XTCE example you provided above the DynamicValue doesn't have a value to extract that I can see.  Am I missing something?

**Comment by bbrisnehan** [comment]
I apologize, I had to remove any/all proprietary information and was more conservative to avoid providing too much information.  These are the formats that we tend to implement:

`<DynamicValue>
    <ParameterInstanceRef parameterRef="..."/>
    <LinearAdjustment intercept="-1"/>
</DynamicValue>`

`<DynamicValue>
    <ParameterInstanceRef parameterRef="..."/>
    <LinearAdjustment slope="1" intercept="-1"/>
</DynamicValue>`

`<DynamicValue>
    <ParameterInstanceRef parameterRef="..."/>
</DynamicValue>`

Let me know if this clarifies or additional insight is needed.  Thank you for your help.

**Comment by bbrisnehan** [comment]
I was working through making all of my abstract MetaCommands into abstract CommandContainers/SequenceContainers.  I was facing issues with ArgumentRefEntry in a CommandContainer, and began looking around.  In my search I found these two presentations:

https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20100015491.pdf
https://www.astro.umd.edu/~eshaya/XTCE/XTCE_Tutorial.ppt

Slide 60 - 61 of the first deck and Slide 23 of the second deck are what I'm trying to achieve with an abstract MetaCommand.  Is this supported?

**Comment by bawi235** [comment]
Is this still an active issue?

**Comment by bbrisnehan** [comment]
Issue is still open and no further comments made here, so yes I believe so.

**Comment by bawi235** [comment]
I attempted to import both of the files you listed above using version 1.5.38 of CCDD and both imported without error. I would suggest trying this version yourself to see if it works as you expect. Keep in mind that CCDD supports a limited sort of XTCE, tailored for use by the display group who work(ed) the Habitat project.  The only guarantee is that CCDD can import its own exported XTCE files.  XTCE that's formatted differently won't work.  XTCE "features" not already covered in CCDD's XTCE parser will be ignored (or maybe cause odd behavior).
