### ISSUE TITLE
CCDD v2 doesn't work with Java 11

### ISSUE THREAD

**Issue by BaldBeacon** [nasa/CCDD#67]
It's not currently mentioned in the documentation that Java 8 is required for CCDD v2 and newer versions of Java won't work. This should be included somewhere in the readme for the project.

**Comment by bawi235** [comment]
Just wanted to provide an update to this issue. We currently have an open issue to get CCDD working with newer versions of Java while still working with Java 7-10.

**Comment by bawi235** [comment]
CCDD version 1 and 2 now work with java 7-13
