### ISSUE TITLE
[Feature Request] Replace Existing Script Associtation Flag

### ISSUE THREAD

**Issue by amikhail0** [nasa/CCDD#69]
It would be helpful if there was a command line flag to replace any imported script association configuration

**Comment by jmacneal** [comment]
@amikhail0 I assume you mean an import flag, and that this would be an analogous command line flag `replaceExistingMacros`. Right now, any conflicting script association definition between the current database and an attempted import will ignore the conflicting imports.

**Comment by amikhail0** [comment]
@jmacneal That's exactly what I meant. A flag like "replaceExistingMacros" should do address this for me.

I actually get script association errors when importing conflicting script association definitions

**Comment by bawi235** [comment]
This change will be included in our next release.

**Comment by bawi235** [comment]
Version 2.0.23 is out and includes this new functionality.
