### ISSUE TITLE
Incorrect documentation for isDataTypePrimitive and isStructureShared

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#7]
The contents of the 'Description' and 'Input(s)' columns of the table on page 174 of the users guide appears to be swapped for rows describing the methods isDataTypePrimitive and isStructureShared.

The description/input for isStructureShared references datatypes and the description/input for isDataTypePrimitive references structures. Appears that swapping the rows would solve the issue.

Noted in user guide Version 1.1.50.

**Comment by KevinMcCluney** [comment]
The description and input text for these two methods has been corrected; this change will appear in the next version of the guide uploaded.  Good catch!
