### ISSUE TITLE
CRITICAL: Filesystem Directory Deletion possible

### ISSUE THREAD

**Issue by MauriceS-gti** [nasa/CCDD#74]
I installed CCDD locally on my Linux Desktop, in order to add TLM/CMD data. Then I tried a export it to a file (it was either JSON or CSV, i don't remember) and browsed to my home directory. I forgot to add a filename at the end, and started the operation (my mistake). The app started deleting the contents of my home directory. I'll work on some fixes once my machine is back operational.

**Comment by bawi235** [comment]
Sorry for the inconvenience this may have caused. This is a major bug and we are working to get a solution out today. We will add another option to the export GUI that allows the user to choose if they wish to delete all contents of the target directory. Will post an update once the fix is pushed.

**Comment by bawi235** [comment]
I have pushed a fix that addresses the problem you encountered. There is a new checkbox that allows you to choose if you wish to delete the contents of the target directory during an export. Closing this issue.
