### ISSUE TITLE
C_Struct_To_CSV output cannot be imported in CCDD-2

### ISSUE THREAD

**Issue by MauriceS-gti** [nasa/CCDD#75]
I have setup CCDD 2.0 locally on a system here, and am using the
struct parser to parse a cFS project. When I try to import the CSV
files generated in CCDD it fails consistently. I have attached a
sample file and the relevant error log.
This is running against a PostgreSQL 11 instance.

[error.log](https://github.com/nasa/CCDD/files/4461990/error.log)

[cFS_CS_tables.txt](https://github.com/nasa/CCDD/files/4461994/cFS_CS_tables.txt)

It complains about 'Structure'

**Comment by bawi235** [comment]
I was able to import the tables listed above with no issue, but I am using a machine with postgreSQL 9.4. Going to set up a VM with postgreSQL 11 and give it another test as I have never tried anything above 9.6 and can not verify it works yet. Will post an update when I can.

**Comment by bawi235** [comment]
I just published version 2.0.20 of CCDD. I would try the import above again and see if it works as expected. I will leave this issue open for another week to see if you are still encountering problems. If not I will close it at that time.
