### ISSUE TITLE
Backup cannot be restored on an empty database

### ISSUE THREAD

**Issue by MauriceS-gti** [nasa/CCDD#76]
Running CCDD in a docker environment, and was trying to downgrade to an older version, i made a backup before from a postgreSQL 11 instance, and when the I couldn't downgrade, I switched back to 11, tried to restore the attached file, and it failed.
[test_dbu.zip](https://github.com/nasa/CCDD/files/4473038/test_dbu.zip)
user = testuser

**Comment by bawi235** [comment]
This is related to your last issue. As is, CCDD does not support PSQL11 and will not work with it. pg_dump changed with psql 11 and information that is needed to restore the dbu file is no longer dumped. I am working on some changes now that will allow CCDD to work with PSQL 8.4-11. It may be a few days before this change is committed to this repo, but I will update you once it is.

**Comment by bawi235** [comment]
I just published version 2.0.20 of CCDD. I would try the restore again and see if everything is now working as expected. I will leave this issue open for another week to see if you are still encountering problems. If not I will close it at that time. Sorry it took longer than expected for this release.
