### ISSUE TITLE
Project->New does not create tables

### ISSUE THREAD

**Issue by ceres-robotics** [nasa/CCDD#78]
Project->New completes successfully and I can see in psql that the database was created but it has no tables:

postgres=# \c test6
You are now connected to database "test6" as user "postgres".
test6=# \dt
Did not find any relations.
test6=# 

When I try to open this project, I get a bunch of errors:

18 | localhost5432 | test7 | tklaus | 06/26/202014:22:44.127 | Command | SELECT obj_description('public.__tlm_scheduler'::regclass, 'pg_class');
-- | -- | -- | -- | -- | -- | --
19 | localhost5432 | test7 | tklaus | 06/26/202014:22:44.352 | Fail | Cannot obtain comment for table '__tlm_scheduler'; cause 'Invalid SQL command; ERROR: relation "public.__tlm_scheduler" does not exist  Position: 24'
20 | localhost5432 | test7 | tklaus | 06/26/202014:22:48.847 | Fail | Invalid rate parameter(s): using default values instead; cause 'missing rate value'

It seems that CCDD never creates the schema?

**Comment by bawi235** [comment]
Thanks for bringing this to our attention. I will be releasing a fix in the next few days.

**Comment by bawi235** [comment]
Version 2.0.22 of CCDD has been released which addresses this problem. I will leave this issue open for another week or so to give you time to work with the new version. If you encounter any problems let us know and we will do our best to address them.
