### ISSUE TITLE
isStructureShared returns true for structure with only one parent

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#8]
I'm not sure if I'm misunderstanding the documentation for the isStructureShared method, or if there is a bug with the implementation. The documentation for isStructureShared states: "Determine if the specified structure is referenced by more than one parent structure". 

In my database, I have a structure 'PriHdr' which is a field in 'TlmHdr' which is a field in multiple other structures. PriHdr only has one parent (TlmHdr) whereas TlmHdr has many parents, however isStructureShared returns true for both. 

I also have a structure 'TestData' which is a field in 'TestPkt'. TestPkt has no parents and TestData only has TestPkt as a parent. As expected, isStructureShared returns false for both.

The current implementation appears to determine if a structure has multiple root tables as ancestors, not multiple parents (based on the terminology defined in section 4.5.1). It would be helpful to clarify the documentation so that its consistent with the definitions earlier in the guide. 

My application is that I am attempting to generate a database for COSMOS (http://cosmosrb.com/). For data structures which are utilized within multiple packets, they recommend defining the structure once in a separate file and using render (http://cosmosrb.com/news/2016/09/12/erb-config/) to include in where needed in the packet definition. Only in the case that a structure has multiple parents is it necessary to create a new file, which I was attempting to use isStructureShared to detect. In this application, its undesirable to detect if a structure has multiple ancestors because it only needs to be placed in a separate file if it has multiple parents. If isStructureShared is not the appropriate method to detect a single parent, could you suggest an alternative method?

**Comment by KevinMcCluney** [comment]
This method should return 'false' if the target structure is referenced by only one root structure.  A recent change in how the variable paths are collected resulted in the method detecting an extraneous root structure.  The issue has been corrected and will appear in the next release of the application (version >= 1.1.55).  The documentation for isStructureShared() is also updated to correctly specify 'root', and not 'parent' structure.
