### ISSUE TITLE
Enum tables are returned by some CcddScriptDataAccessHandler structure table calls

### ISSUE THREAD

**Issue by royerboat** [nasa/CCDD#85]
The newly added Enum tables seem to be included in a couple of the CcddScriptDataAccessHandler calls that return information for Structures, specifically the `getStructureTablesByReferenceOrder` and `getStructureTableNumRows` functions.

I tested this out by doing the following:
1. Updating an existing project to use CCDD v2.0.24
2. Adding a new ENUM table
3. Replacing a row in a structure table to use the new enum table I created.
4. Running the typesHeader.js script that is included in the CCDD scripts folder.

I initially get some errors about variables not existing, but after fixing those errors it includes an empty enum as a structure. This script would need to be updated to handle enum tables, but the `getStructureTablesByReferenceOrder` seems to be returning an enum table along with the other structure tables.

**Comment by bawi235** [comment]
Great catch! I did not think about the other data access methods retrieving the ENUM tables when I added them. I will try to get a quick fix for this out sometime tomorrow.

**Comment by bawi235** [comment]
Pushed a quick fix. Will leave this issue open incase you run into more issues.

**Comment by royerboat** [comment]
Thanks for the quick fix. This addresses the issue I was running into. I've updated a copy of the typesHeader.js script to output enums as well, here is a quick diff of the changes I made:

```diff
--- ../CCDD/scripts/typesHeader.js      2020-09-30 18:02:56.247331600 -0500
+++ ccdd/scripts/typesHeader.js 2020-10-13 12:47:45.454220600 -0500
@@ -40,6 +41,8 @@
 // Get an array containing the data stream names
 var dataStreams = ccdd.getDataStreamNames();

+var enumNames = ccdd.getEnumTableNames();
+
 /** Functions *************************************************************** */

 /*******************************************************************************
@@ -68,6 +71,36 @@
     ccdd.writeToFileLn(file, "*/\n");
 }

+function outputEnum(file, index)
+{
+    var lastEnumEntry = 0;
+
+    if (index < 0) {
+        return;
+    }
+
+    ccdd.writeToFileLn(file, "typedef enum");
+    ccdd.writeToFileLn(file, "{");
+
+    var data = ccdd.getEnumTableData(enumNames[index]);
+    var length = data.length;
+    var lastEnumEntry = length - 1;
+
+    for (var i = 0; i < data.length; i++)
+    {
+        if (lastEnumEntry == i)
+        {
+            ccdd.writeToFileLn(file, "   " + data[i]);
+        }
+        else
+        {
+            ccdd.writeToFileLn(file, "   " + data[i] + ",");
+        }
+    }
+
+    ccdd.writeToFileLn(file, "} " + enumNames[index] + ";");
+}
+
 /*******************************************************************************
  * Output a structure's type definition to the specified file
  *
@@ -467,6 +500,13 @@

         ccdd.writeToFileLn(typesFile, "");

+        // Step through the enums
+        for (var enumIndex = 0; enumIndex < enumNames.length; enumIndex++)
+        {
+            outputEnum(typesFile, enumIndex);
+            ccdd.writeToFileLn(typesFile, "");
+        }
+
         // Step through each structure. This list is in reference order so that
         // base structures are created before being referenced in another
         // structure
```

**Comment by bawi235** [comment]
I will add this script to the repo. Thanks for making the changes!

**Comment by royerboat** [comment]
I just noticed a possible issue.

I've created a few ENUM tables and associated them with different groups. I also have a script (the typesHeader.js which I had modified above) that is associated with one group. When I run that script, I'm getting all of the ENUM tables outputted to the resulting header file, not just the ENUM tables associated with specified group.

I was under the impression that the scripts would only work with the tables associated with that script, which doesn't seem to be the case for the ENUM tables. Is that intended?

**Comment by bawi235** [comment]
I will change the data access methods so that they only return enum tables which are members off a group associated with the script being executed. I should have this fix out early next week along with other updates that will close all your open issues.

**Comment by bawi235** [comment]
I updated the enum data access methods as you requested and pushed the updated typeHeader.js file to the repo.
