### ISSUE TITLE
Feature Request: Toggle expanding of groups/parents so that you can collapse them

### ISSUE THREAD

**Issue by royerboat** [nasa/CCDD#87]
The "Expand All" checkbox does it's job well. It would be nice if this acted more like a toggle though and would collapse the groups/parents making it easier to navigate to a particular group/parent. So check "Expand All" to expand all and uncheck it to collapse all. This is just one way to add in the collapse feature using an existing piece of user interface.

**Comment by bawi235** [comment]
To be quite frank it is supposed to work that way. Older versions of CCDD toggle just as you are referring to, but it appears I may have broke the functionality somehow. I will push a fix for this soon.

**Comment by bawi235** [comment]
I have pushed an update that fixes the table tree expansion issue. Thanks for the feedback on this one.
