### ISSUE TITLE
getStructureTablesByReferenceOrder not returning tables with type "Structure: Cmd Args Ref"

### ISSUE THREAD

**Issue by royerboat** [nasa/CCDD#88]
The `getStructureTablesByReferenceOrder` function from the` CcddScriptDataAccessHandler` class no longer seems to return tables where the type is "Structure: Cmd Args Ref".

You can see this when trying to run the typesHeader.js script against a command that include a command args structure. The data type for the command args structure does not appear in the header file output.

**Comment by bawi235** [comment]
Pushed an update that addresses this issue.

**Comment by royerboat** [comment]
Thanks, this seems to resolve my issue.
