### ISSUE TITLE
Git-based CCDD Workflow - Request for Import/Export commands

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#9]
I'm looking at using CCDD for a project which utilizes git as its code's CM system. The goal is to use CCDD to generate the interface artifacts (header files, ground system definitions, ICDs, etc) using the CCDD scripting interfaces. By git's nature, there may be multiple branches of the code which have different versions of an interface and it may be necessary to generate the interface artifacts for a particular branch. Can you suggest how to best utilize CCDD in this scenario?

My understanding is that the import/export when using the JSON and CSV formats is lossless (ie, its an exact definition of the database). My thought is to export the CCDD database and commit that to the git branch it describes. When a developer needs to make an interface change to a particular branch they'd import the database from that branch into CCDD, make the change, generate their artifacts, and then export the database and commit the new version of the database to their branch. 

I believe this workflow offers the best of both worlds... managing the interface definition with the code that it represents while utilizing CCDD as the editing interface (to maintain database consistency) and leveraging it's scripting interfaces to generate the required artifacts.

I don't currently see a way to automate importing and exporting databases... this workflow could be almost entirely automated if the CCDD executable supported an 'import' and 'export' command which provided similar functionality to the respective dialogs. Is this something that is on the development roadmap?

Thanks

**Comment by KevinMcCluney** [comment]
The backup and restore commands (in the Project menu) are the best option for storing and retrieving a snapshot of the entire project database (including any stored scripts).  There is a command line option to backup a project, allowing that operation to be automated.

**Comment by KevinMcCluney** [comment]
I don't understand the need to edit the file created by the backup (pg_dump) - I thought this was only for storage in a bit repo.  I don't recommend editing the dump manually.  I recommend all editing be done via the program GUI rather than rely on importing. There isn't a good method to catalog differences between two databases. A diff of the backup, csv, or json files would give you an idea of the changes, but interpreting the differences could be a challenge (out time consuming).
I'm actually on vacation until 6/4, so I'll be able to address questions better when I get back to the office.

**Comment by ascended121** [comment]
There are numerous existing tools which can assist with diffing/merging text content, so the idea was to leverage those for dealing with multiple versions of a definition of an interface. Those tools typically have functionality which allows the user to select which version of a particular line they'd like to keep, which saves them from having to re-type the content or copy-paste. I agree that the GUI would be the safest entry mechanism, but it requires that a user re-type all the changes into the GUI, which could be error prone and time consuming.

Apologies for interrupting your time off, this can wait until you return. Enjoy the rest of your vacation.

**Comment by KevinMcCluney** [comment]
I'm adding command line commands for import and export - these may be operational by the end of the week.

**Comment by KevinMcCluney** [comment]
Command line commands for import and export have been added.  The command line usage text briefly describes these new commands,  The user's guide will be updated soon to fully describe how these commands operate.

**Comment by ascended121** [comment]
I haven't yet been able to figure out the delimiters/format for sub-commands, and thus haven't been able to try the CLI import/export... could you explain them briefly to tide me over until the official documentation is released? Thanks

**Comment by KevinMcCluney** [comment]
The latest version of the user's guide has some more information on the command line usage.
Here are some examples:
  export “-tablePaths table1Name -filePath /user/name/exportFolder -shutdown”
  export '-shutdown -filePath /exports -tablePaths Group:tableGroup -format json -overwriteFile true'
  import '-fileName importFile -openEditor true -replaceExisting true'

Note that the import/export sub-commands must be bounded by single or double quotes; otherwise they conform to the 'normal' command line argument constraints.

**Comment by ascended121** [comment]
Thanks, I'll take a look at the updates. From the above examples though, as far as I can tell, the shutdown command must be outside the export subcommand, otherwise its not recognized.

Please let me know if you'd like to take the following into separate issues:

When attempting to export I'm getting the following unhandled exception. It appears to occur any time I omit the filePath subcommand, which the documentation implies is optional for csv outputs.

```
> java -cp "my\Path\To\CCDD.jar" CCDD.CcddMain -logPath "my\Log\Path" -project myProject -user myUser -password myPassword -export "-format csv -singleFile true -tablePaths Group:myGroupName" -shutdown
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at CCDD.CcddUtilities.removeTrailer(CcddUtilities.java:875)
        at CCDD.CcddFileIOHandler.exportSelectedTables(CcddFileIOHandler.java:2216)
        at CCDD.CcddCommandLineHandler$24.doCommand(CcddCommandLineHandler.java:1070)
        at CCDD.CcddCommandLineHandler$CommandHandler.handler(CcddCommandLineHandler.java:365)
        at CCDD.CcddCommandLineHandler.parseCommand(CcddCommandLineHandler.java:1686)
        at CCDD.CcddCommandLineHandler.parseCommand(CcddCommandLineHandler.java:1573)
        at CCDD.CcddMain.parseDbSpecificCommandLineCommands(CcddMain.java:762)
        at CCDD.CcddDbControlHandler$2.complete(CcddDbControlHandler.java:2276)
        at CCDD.CcddBackgroundCommand$1.done(CcddBackgroundCommand.java:192)
        at javax.swing.SwingWorker$5.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
        at sun.swing.AccumulativeRunnable.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

Also when using the filePath subcommand, I can reliable reproduce this error below by using an incorrect path delimiter (note the '/' instead of '\', which would be appropriate for a windows system):

```java -cp "my\Path\To\CCDD.jar" CCDD.CcddMain -logPath "my\Log\Path" -project myProject -user myUser -password myPassword -export "-format csv -filePath ./out/ -singleFile true -tablePaths Group:myGroup" -shutdown
CCDD : CCDD Error : An unanticipated error occurred; cause   'String index out of range: -1'  Error trace:   CcddFileIOHandler: storePath() line 2759   CcddFileIOHandler: exportSelectedTables() line 2409   CcddCommandLineHandler: doCommand() line 1070   CcddCommandLineHandlerCommandHandler: handler() line 365   CcddCommandLineHandler: parseCommand() line 1686   CcddCommandLineHandler: parseCommand() line 1573   CcddMain: parseDbSpecificCommandLineCommands() line 762   CcddDbControlHandler: complete() line 2276   CcddBackgroundCommand: done() line 192```

**Comment by KevinMcCluney** [comment]
You are correct - the shutdown command isn't one of the export sub-commands, so it doesn't go within the quotes.

The filePath command isn't required for the CSV or JSON formats if exporting the tables to individual files.  However, if exporting to a single file the filePath is required for these formats.  The user's guide will be updated to make this clear.

For the last issue it isn't clear what command line string you're referring to.
