### ISSUE TITLE
Invalid SQL command; ERROR: syntax error at or near "OIDS" when opening project

### ISSUE THREAD

**Issue by tstern-masten** [nasa/CCDD#92]
Hello,

I am new to CCDD and PostgreSQL in general. Working through the provided tutorial I get the following error attempting to open the project in my terminal. 

```
Command that failed: CREATE TABLE __dbu_info (database_lock text, database_name text, database_users text, database_description text) WITH OIDS; INSERT INTO __dbu_info VALUES ('Core Flight Software Command and Data Dictionary0', 'MyProject', 'tstern', 'Test'); ALTER TABLE __dbu_info OWNER TO tstern; GRANT ALL PRIVILEGES ON TABLE __dbu_info TO GROUP tstern; 
Command that failed: DELETE FROM __dbu_info;
Command that failed: CREATE TABLE __dbu_info (database_lock text, database_name text, database_users text, database_description text) WITH OIDS; INSERT INTO __dbu_info VALUES ('Core Flight Software Command and Data Dictionary0', 'myproject', 'tstern', 'Test'); ALTER TABLE __dbu_info OWNER TO tstern; GRANT ALL PRIVILEGES ON TABLE __dbu_info TO GROUP tstern; 
```

Digging into logs I see the following complaints as well 
```
|Fail|Cannot create tables and functions in project database 'myproject' as user 'tstern'; cause 'Invalid SQL command; ERROR: syntax error at or near "OIDS"  Position: 119'
```

I am running on a linux VM and have the following versions:
- Java: 11.0.11
- CCDD: 2.0.27 (10-1-2021)
- PostGreSQL: 12.8  *** JDBC: PostgreSQL 9.4.1207.jre7 

After doing some digging it appears that the use of OIDS was removed in version 12 of PostGreSQL. I will roll back and try again. Apologies if this is already documented somewhere.

**Comment by CDKnightNASA** [comment]
Given that "with oids" has been deprecated, seems to me this ticket should remain open until CCDD has a fix to support the latest Postgres?

**Comment by DavidKelly-MDA** [comment]
Agreed. This requires rolling postgres back to a much less secure version.
