### ISSUE TITLE
Cannot Import/Export EDS/XTCE

### ISSUE THREAD

**Issue by tstern-masten** [nasa/CCDD#94]
Hello,

I was able to complete the tutorial (thank you again for the help with #93) and am now trying to interface CCDD with my cFS repository.

I first attempted to import a provided EDS from the cFS repo, [base_types.xml](https://github.com/nasa/cFE/blob/b66661cc6e8f695d5ca9fa56217f58a291d5884d/modules/core_api/eds/base_types.xml), which resulted in nothing happening. I can see in logs it attempts to import but I do not get any indication of errors. (Note: I tried with both .xml and .eds extensions)
```
localhost:5432|cFS|tstern|11/10/2021 09:56:20.453|Status|Importing table(s) from '/home/tstern/NASA/cFS/cfe/fsw/cfe-core/eds/base_types.eds'
localhost:5432|cFS|tstern|11/10/2021 09:56:20.453|Command|SELECT 1 FROM pg_tables WHERE tablename ~* E'^__groups$';
localhost:5432|cFS|tstern|11/10/2021 09:56:20.454|Command|SELECT * FROM __groups ORDER BY OID;
```
I see the exact same behavior when trying to import XTCE as well.

Trying to export XTCE or EDS, I do not get any output to logs at all and no indication of a failure. 

C_Headers and CSV both work without issue on import/export. I have not tested JSON import but export works there as well.

I did notice that the default schema locations in the Preferences->Other tab for both XTCE and EDS were 404 links so I updated those to live xsd pages which could be part of my issue if I did incorrectly. For reference I used "https://www.omg.org/spec/XTCE/20180204/SpaceSystem.xsd" as my XTCE xsd. 

I also noticed this is very similar to the behavior seen in #91

I would greatly apricate any and all help and am happy to assist in whatever way possible.

**Comment by tstern-masten** [comment]
Also a small side issue. I was trying to recompile the java .jar but I keep getting an error message
```
/home/tstern/NASA/CCDD/ccdd.build.xml:13: The archive jar-in-jar-loader.zip doesn't exist
```
when running ant -f ccdd.build.xml

From the googling I did it seems that is an archive that eclipse creates. Does the jar need to be generated in eclipse and if so is there a specific version requirement?

**Comment by KevinMcCluney** [comment]
The CCDD EDS and XTCE formats support import and export of structure and command table data only.  The example file noted (base_types.xml) does not contain a table definition, so CCDD created nothing from the imported file.  Note the format of the EDS and XTCE tables is specific to CCDD; in other words, CCDD can import files that were exported by CCDD, but not necessarily from other sources.  See the user's guide sections 4.8.3.7, Import data and 4.8.3.8, Export data.

**Comment by KevinMcCluney** [comment]
jar-in-jar-loader.zip has been added to the repo.
